(function(){
  var stateKey='etb2b_awards.certificates.v15';
  var award={name:'India FinTech Awards 2027'};try{var a=JSON.parse(localStorage.getItem('etb2b_awards_new_award')||'null');if(a&&a.name)award=a}catch(e){}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function loadRegistry(){try{var s=JSON.parse(localStorage.getItem(stateKey)||'null');return s&&s.generated?s.generated:{}}catch(e){return{}}}
  function dateLabel(v){if(!v)return'—';var d=new Date(v+'T00:00:00');return d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
  function findByCode(code){var reg=loadRegistry(),found=null;Object.keys(reg).some(function(id){if(String(reg[id].code||'').toUpperCase()===String(code||'').trim().toUpperCase()){found=reg[id];return true}return false});return found}
  function render(code){var root=document.getElementById('verifyResult'),r=findByCode(code);if(!code){root.innerHTML='<div class="verify-empty"><span>⌁</span><b>Enter a certificate ID above</b><p>Generated certificates from this manager demo are stored in your current browser.</p></div>';return}if(!r){root.innerHTML='<div class="invalid-card"><div class="invalid-icon">!</div><h2>Certificate not found</h2><p>We could not find <b>'+esc(code.toUpperCase())+'</b> in this browser\'s ETB2B Awards certificate registry. Check the ID and try again.</p></div>';return}root.innerHTML='<article class="valid-card"><div class="valid-top"><div class="valid-check">✓</div><div><small>VERIFIED CERTIFICATE</small><h2>Valid ETB2B Awards certificate</h2><p>This certificate ID matches a generated record in the award registry.</p></div></div><div class="valid-body"><div class="valid-recipient"><small>AWARDED TO</small><h3>'+esc(r.recipient)+'</h3><span class="valid-level">'+esc(String(r.award||'Winner').toUpperCase())+'</span><div class="valid-category">'+esc(r.category)+'</div></div><div class="valid-grid"><div><small>Certificate ID</small><b>'+esc(r.code)+'</b></div><div><small>Issue date</small><b>'+esc(dateLabel(r.issueDate))+'</b></div><div><small>Issuing award</small><b>'+esc(award.name)+'</b></div><div><small>Status</small><b>Valid · Generated</b></div></div></div></article>'}
  document.getElementById('verifyForm').addEventListener('submit',function(e){e.preventDefault();var code=document.getElementById('verifyCode').value.trim();render(code);if(code)history.replaceState(null,'','?id='+encodeURIComponent(code))});
  var params=new URLSearchParams(location.search),code=params.get('id')||'';if(code){document.getElementById('verifyCode').value=code;render(code)}
})();
