(function(){
  var $=function(s){return document.querySelector(s)};
  var $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
  var stateKey='etb2b_awards.certificates.v15';
  var winnersKey='etb2b_awards.winners.v13';
  var activeRecipientId=null;
  var filter='all';
  var award={name:'India FinTech Awards 2027',description:'Recognising excellence and innovation across India\'s fintech ecosystem.',slug:'india-fintech-awards-2027'};
  try{var a=JSON.parse(localStorage.getItem('etb2b_awards_new_award')||'null');if(a&&a.name)award=a}catch(e){}
  var year=((award.name||'').match(/20\d{2}/)||['2027'])[0];
  var initialsAward=(award.name||'ETB2B Awards').split(/\s+/).map(function(x){return x.charAt(0)}).join('').replace(/[^A-Za-z]/g,'').slice(0,2).toUpperCase()||'AF';

  var defaults={template:'classic',primary:'#241a44',accent:'#c9a85b',title:'Certificate of Excellence',copy:'In recognition of outstanding achievement, innovation and contribution to the future of financial technology.',signatureOneName:'Aarav Kapoor',signatureOneTitle:'Program Director',signatureTwoName:'Maya Shah',signatureTwoTitle:'Jury Chair',signatureOneImage:'',signatureTwoImage:'',verification:true,emailDelivery:true,issueDate:'2027-06-15',generated:{},deliveryPrepared:false};
  var state=JSON.parse(JSON.stringify(defaults));
  function merge(t,s){Object.keys(s||{}).forEach(function(k){if(s[k]&&typeof s[k]==='object'&&!Array.isArray(s[k])&&t[k]&&typeof t[k]==='object'&&!Array.isArray(t[k]))merge(t[k],s[k]);else t[k]=s[k]});return t}
  function load(){try{var s=JSON.parse(localStorage.getItem(stateKey)||'null');if(s)merge(state,s)}catch(e){}}
  function save(show){try{localStorage.setItem(stateKey,JSON.stringify(state));if(show)toast('Certificate settings saved')}catch(e){}}
  function toast(msg){var el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__certToast);window.__certToast=setTimeout(function(){el.classList.remove('show')},2100)}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function initials(name){return String(name||'W').split(/\s+/).map(function(x){return x.charAt(0)}).join('').replace(/[^A-Za-z]/g,'').slice(0,2).toUpperCase()||'W'}
  function awardLabel(v){var m={winner:'Winner','runner-up':'Runner-up',gold:'Gold','silver':'Silver','bronze':'Bronze'};return m[v]||'Winner'}
  function isAward(v){return ['winner','runner-up','gold','silver','bronze'].indexOf(v)>-1}
  function verified(f){return !!(f.nameVerified&&f.brandVerified&&f.consent&&f.juryApproved)}

  var baseCategories=[
    {id:'startup',name:'Best FinTech Startup',locked:false,finalists:[{id:'nova',name:'NovaPay Technologies',tag:'Digital-first payment infrastructure',award:'winner',email:'winner@novapay.example',nameVerified:true,brandVerified:true,consent:false,juryApproved:true},{id:'cred',name:'CredStack',tag:'Embedded credit infrastructure',award:'finalist',email:'team@credstack.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true},{id:'astra',name:'AstraLedger',tag:'SME treasury automation',award:'finalist',email:'awards@astraledger.example',nameVerified:true,brandVerified:false,consent:true,juryApproved:true}]},
    {id:'lending',name:'Best Digital Lending',locked:true,finalists:[{id:'clearlend',name:'ClearLend',tag:'Embedded SME credit platform',award:'winner',email:'awards@clearlend.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true},{id:'creditnova',name:'CreditNova',tag:'Alternative risk engine',award:'finalist',email:'hello@creditnova.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true}]},
    {id:'payments',name:'Best Payments Innovation',locked:true,finalists:[{id:'paymesh',name:'PayMesh',tag:'Programmable merchant payments',award:'winner',email:'awards@paymesh.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true},{id:'tapgrid',name:'TapGrid',tag:'Offline-first acceptance network',award:'finalist',email:'team@tapgrid.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true}]},
    {id:'ai',name:'Best AI in Financial Services',locked:false,finalists:[{id:'riskmind',name:'RiskMind AI',tag:'Explainable underwriting intelligence',award:'finalist',email:'hello@riskmind.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:false},{id:'finpilot',name:'FinPilot Labs',tag:'AI operations copilot for banks',award:'finalist',email:'awards@finpilot.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:false}]},
    {id:'leader',name:'FinTech Leader of the Year',locked:true,finalists:[{id:'neha',name:'Neha Rao - Orbit Finance',tag:'Founder and CEO',award:'winner',email:'neha@orbitfinance.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true},{id:'arjun',name:'Arjun Mehta - NovaPay',tag:'Co-founder',award:'finalist',email:'arjun@novapay.example',nameVerified:true,brandVerified:true,consent:true,juryApproved:true}]}
  ];

  function loadWinnerState(){var cats=JSON.parse(JSON.stringify(baseCategories));try{var s=JSON.parse(localStorage.getItem(winnersKey)||'null');if(s&&s.categories){s.categories.forEach(function(sc){var c=cats.filter(function(x){return x.id===sc.id})[0];if(!c)return;if(typeof sc.locked==='boolean')c.locked=sc.locked;if(sc.finalists)sc.finalists.forEach(function(sf){var f=c.finalists.filter(function(x){return x.id===sf.id})[0];if(!f){f={id:sf.id,name:sf.name||sf.id,tag:'',email:'winner@etb2b_awards.example'};c.finalists.push(f)}Object.keys(sf).forEach(function(k){if(k!=='id')f[k]=sf[k]})})})}}catch(e){}return cats}
  var categories=loadWinnerState();
  function allAwardRecipients(){var out=[];categories.forEach(function(c){c.finalists.forEach(function(f){if(isAward(f.award))out.push({id:c.id+'::'+f.id,categoryId:c.id,category:c.name,categoryLocked:c.locked,name:f.name,email:f.email||('winner@'+String(f.id).replace(/[^a-z0-9]/gi,'').toLowerCase()+'.example'),tag:f.tag||'',award:f.award,verified:verified(f),source:f})})});return out}
  function eligible(){return allAwardRecipients().filter(function(r){return r.categoryLocked&&r.verified})}
  function protectedRecipients(){return allAwardRecipients().filter(function(r){return !(r.categoryLocked&&r.verified)})}
  function findRecipient(id){return allAwardRecipients().filter(function(r){return r.id===id})[0]||null}

  function syncBrandKit(silent){try{var slug=award.slug||String(award.name||'award').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');var website=JSON.parse(localStorage.getItem('etb2b_awards_website_'+slug)||'null');if(website){if(website.primary)state.primary=website.primary;if(website.accent)state.accent=website.accent;if(!silent)toast('Brand Kit colors synced from Website Builder')}else if(!silent){toast('No saved Brand Kit found — using certificate colors')}}catch(e){if(!silent)toast('Brand Kit could not be read')}renderControls();renderPreview()}
  function dateLabel(v){if(!v)return'';var d=new Date(v+'T00:00:00');return d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
  function codeFor(r){var existing=state.generated[r.id];if(existing&&existing.code)return existing.code;var awardCode=(award.name||'IFA').split(/\s+/).map(function(x){return x.charAt(0)}).join('').replace(/[^A-Za-z0-9]/g,'').slice(0,5).toUpperCase();var yy=String(year).slice(-2);var person=String(r.name).replace(/[^A-Za-z0-9]/g,'').slice(0,6).toUpperCase();var suffix=(Math.abs(hash(r.id))%900+100);return awardCode+yy+'-'+person+'-'+suffix}
  function hash(s){var h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h+=(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24)}return h|0}
  function drawMatrix(canvas,text){if(!canvas)return;var ctx=canvas.getContext('2d'),n=21,size=canvas.width,cell=size/n;ctx.clearRect(0,0,size,size);ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);var seed=Math.abs(hash(text));function finder(x,y){ctx.fillStyle='#111';ctx.fillRect(x*cell,y*cell,7*cell,7*cell);ctx.fillStyle='#fff';ctx.fillRect((x+1)*cell,(y+1)*cell,5*cell,5*cell);ctx.fillStyle='#111';ctx.fillRect((x+2)*cell,(y+2)*cell,3*cell,3*cell)}finder(0,0);finder(14,0);finder(0,14);for(var yy=0;yy<n;yy++){for(var xx=0;xx<n;xx++){if((xx<8&&yy<8)||(xx>12&&yy<8)||(xx<8&&yy>12))continue;seed=(seed*1664525+1013904223)>>>0;if(((seed>>>28)&1)===1){ctx.fillStyle='#111';ctx.fillRect(Math.floor(xx*cell),Math.floor(yy*cell),Math.ceil(cell),Math.ceil(cell))}}}}
  function selectedRecipient(){var r=findRecipient(activeRecipientId);if(r&&r.categoryLocked&&r.verified)return r;var list=eligible();return list[0]||allAwardRecipients()[0]||null}

  function renderControls(){
    $$('#templateGrid [data-template]').forEach(function(b){b.classList.toggle('active',b.dataset.template===state.template)});
    $('#primaryColor').value=state.primary;$('#accentColor').value=state.accent;$('#primaryHex').textContent=state.primary.toUpperCase();$('#accentHex').textContent=state.accent.toUpperCase();
    $('#certificateTitle').value=state.title;$('#certificateCopy').value=state.copy;$('#signatureOneName').value=state.signatureOneName;$('#signatureOneTitle').value=state.signatureOneTitle;$('#signatureTwoName').value=state.signatureTwoName;$('#signatureTwoTitle').value=state.signatureTwoTitle;$('#enableVerification').checked=!!state.verification;$('#emailDelivery').checked=!!state.emailDelivery;$('#issueDate').value=state.issueDate;
  }
  function renderPreview(){var r=selectedRecipient();if(!r)return;activeRecipientId=r.id;var root=$('#certificatePreview');root.className='certificate-preview template-'+state.template;root.style.setProperty('--cp',state.primary);root.style.setProperty('--ca',state.accent);$('#certLogo').textContent=initialsAward;$('#certKicker').textContent=(award.name||'AWARD').toUpperCase();$('#certTitle').textContent=state.title;$('#certRecipient').textContent=r.name;$('#certLevel').textContent=awardLabel(r.award).toUpperCase();$('#certCategory').textContent=r.category;$('#certCopy').textContent=state.copy;$('#sigOneName').textContent=state.signatureOneName;$('#sigOneTitle').textContent=state.signatureOneTitle;$('#sigTwoName').textContent=state.signatureTwoName;$('#sigTwoTitle').textContent=state.signatureTwoTitle;$('#sigOneImage').style.backgroundImage=state.signatureOneImage?'url("'+state.signatureOneImage+'")':'';$('#sigTwoImage').style.backgroundImage=state.signatureTwoImage?'url("'+state.signatureTwoImage+'")':'';var code=codeFor(r);$('#certCode').textContent=code;$('#certIssued').textContent='Issued '+dateLabel(state.issueDate);$('#verificationBlock').style.display=state.verification?'flex':'none';drawMatrix($('#verifyMatrix'),code);$('#previewRecipientLabel').textContent=r.name+' · '+r.category}
  function renderStats(){var list=eligible(),gen=list.filter(function(r){return state.generated[r.id]}),ready=gen.filter(function(r){return state.emailDelivery});$('#eligibleCount').textContent=list.length;$('#generatedCount').textContent=gen.length;$('#readySendCount').textContent=ready.length;$('#verifyStatus').textContent=state.verification?'ON':'OFF';$('#protectedCount').textContent=protectedRecipients().length+' protected winner record'+(protectedRecipients().length===1?'':'s');$('#deliveryReadiness').textContent=ready.length+' ready'}
  function filteredRecipients(){var q=$('#recipientSearch').value.trim().toLowerCase();return eligible().filter(function(r){var gen=!!state.generated[r.id];if(filter==='generated'&&!gen)return false;if(filter==='pending'&&gen)return false;if(q&&(r.name+' '+r.category+' '+awardLabel(r.award)).toLowerCase().indexOf(q)<0)return false;return true})}
  function renderRows(){var root=$('#certificateRows');var list=filteredRecipients();root.innerHTML=list.map(function(r){var g=state.generated[r.id],ready=g&&state.emailDelivery;return '<tr data-row="'+esc(r.id)+'"><td><input class="recipient-check" type="checkbox" data-select-recipient="'+esc(r.id)+'" checked></td><td><div class="recipient-cell"><span class="recipient-avatar">'+initials(r.name)+'</span><div><b>'+esc(r.name)+'</b><small>'+esc(r.email)+'</small></div></div></td><td><span class="award-badge">'+esc(awardLabel(r.award))+'</span></td><td>'+esc(r.category)+'</td><td><span class="decision-ok">Locked + verified</span></td><td><div class="cert-state '+(g?'generated':'')+'"><b>'+(g?'Generated':'Not generated')+'</b><small>'+(g?esc(g.code):'Create certificate ID')+'</small></div></td><td><span class="delivery-state '+(ready?'ready':'')+'">'+(ready?(g.delivery==='queued'?'Email prepared':'Ready'):'—')+'</span></td><td><div class="row-actions"><button data-preview-recipient="'+esc(r.id)+'">Preview</button>'+(g?'<button data-download-recipient="'+esc(r.id)+'">Download</button>':'')+'</div></td></tr>'}).join('');if(!list.length)root.innerHTML='<tr><td colspan="8" style="text-align:center;padding:28px;color:#888">No recipients match this filter.</td></tr>';renderSelectAllState()}
  function renderSelectAllState(){var checks=$$('.recipient-check');$('#selectAll').checked=checks.length>0&&checks.every(function(c){return c.checked})}
  function renderProtected(){var root=$('#protectedList'),list=protectedRecipients();root.innerHTML=list.map(function(r){var reasons=[];if(!r.categoryLocked)reasons.push('decision not locked');if(!r.verified){if(!r.source.nameVerified)reasons.push('public name');if(!r.source.brandVerified)reasons.push('brand permission');if(!r.source.consent)reasons.push('winner consent');if(!r.source.juryApproved)reasons.push('jury approval')}return '<div class="protected-item"><div><b>'+esc(r.name)+'</b><small>'+esc(r.category)+' · '+esc(awardLabel(r.award))+'</small></div><span class="protected-reason">'+esc(reasons.join(' · ')||'Verification incomplete')+'</span></div>'}).join('')||'<div class="protected-item"><b>No protected winner records.</b></div>'}
  function renderHealth(){var list=eligible(),gen=list.filter(function(r){return !!state.generated[r.id]}).length;var checks=[{ok:list.length>0,title:'Winner source connected',note:list.length+' eligible award recipient'+(list.length===1?'':'s')+' synced'},{ok:!!state.title&&!!state.copy,title:'Certificate copy complete',note:'Title and recognition copy are ready'},{ok:!!state.signatureOneName&&!!state.signatureTwoName,title:'Signatures configured',note:'Two approval names are present'},{ok:state.verification,title:'Verification enabled',note:state.verification?'Unique certificate IDs will be issued':'Enable verification for public trust'},{ok:list.length>0&&gen===list.length,title:'Batch generated',note:gen+' of '+list.length+' certificates generated'}];var score=Math.round(checks.filter(function(x){return x.ok}).length/checks.length*100);$('#healthScore').textContent=score+'%';$('#healthBar').style.width=score+'%';$('#healthList').innerHTML=checks.map(function(x){return '<div class="health-item '+(x.ok?'ok':'warn')+'"><span>'+(x.ok?'✓':'!')+'</span><div><b>'+esc(x.title)+'</b><small>'+esc(x.note)+'</small></div></div>'}).join('');var p=protectedRecipients().length;if(!list.length){$('#insightTitle').textContent='No certificate-ready winners yet';$('#insightBody').textContent='Lock a winner decision and complete public verification on the Winners page before issuing certificates.';$('#insightAction').textContent='Review Winners'}else if(gen<list.length){$('#insightTitle').textContent=(list.length-gen)+' approved certificate'+(list.length-gen===1?' is':'s are')+' ready to generate';$('#insightBody').textContent='Generate from the approved winner source so names, award levels and categories stay consistent across every channel.';$('#insightAction').textContent='Generate selected'}else if(p){$('#insightTitle').textContent='Generated certificates are ready — '+p+' winner record'+(p===1?' remains':'s remain')+' protected';$('#insightBody').textContent='You can prepare delivery for generated recipients now. Protected records will stay blocked until decision checks are complete.';$('#insightAction').textContent='Review protected'}else{$('#insightTitle').textContent='Certificate batch is ready for delivery';$('#insightBody').textContent='All eligible award recipients have generated certificate IDs. Review one sample, then prepare winner emails.';$('#insightAction').textContent='Prepare delivery'}return score}
  function renderAll(){renderControls();renderPreview();renderStats();renderRows();renderProtected();renderHealth()}

  function updateFromInputs(){state.primary=$('#primaryColor').value;state.accent=$('#accentColor').value;state.title=$('#certificateTitle').value.trim();state.copy=$('#certificateCopy').value.trim();state.signatureOneName=$('#signatureOneName').value.trim();state.signatureOneTitle=$('#signatureOneTitle').value.trim();state.signatureTwoName=$('#signatureTwoName').value.trim();state.signatureTwoTitle=$('#signatureTwoTitle').value.trim();state.verification=$('#enableVerification').checked;state.emailDelivery=$('#emailDelivery').checked;state.issueDate=$('#issueDate').value;$('#primaryHex').textContent=state.primary.toUpperCase();$('#accentHex').textContent=state.accent.toUpperCase();renderPreview();renderStats();renderRows();renderHealth()}
  function generateRecipient(r){if(!r||!r.categoryLocked||!r.verified)return;var code=codeFor(r);state.generated[r.id]={code:code,recipient:r.name,category:r.category,award:awardLabel(r.award),email:r.email,issueDate:state.issueDate,generatedAt:new Date().toISOString(),delivery:'ready'}}
  function selectedIds(){return $$('.recipient-check:checked').map(function(c){return c.dataset.selectRecipient})}
  function generateSelected(){var ids=selectedIds();if(!ids.length){toast('Select at least one eligible recipient');return}ids.forEach(function(id){generateRecipient(findRecipient(id))});save(false);renderAll();toast(ids.length+' certificate'+(ids.length===1?'':'s')+' generated')}

  function canvasDownload(r){if(!r)return;if(!state.generated[r.id])generateRecipient(r);save(false);var g=state.generated[r.id],canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1132;var ctx=canvas.getContext('2d'),cp=state.primary,ca=state.accent;function txt(text,x,y,size,font,fill,align,weight){ctx.fillStyle=fill;ctx.textAlign=align||'center';ctx.font=(weight?weight+' ':'')+size+'px '+font;ctx.fillText(text,x,y)}function wrap(text,x,y,maxWidth,lineHeight,fontSize,font,fill){ctx.font=fontSize+'px '+font;ctx.fillStyle=fill;ctx.textAlign='center';var words=String(text).split(/\s+/),line='',lines=[];words.forEach(function(w){var test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=w}else line=test});if(line)lines.push(line);lines.slice(0,4).forEach(function(l,i){ctx.fillText(l,x,y+i*lineHeight)})}
    if(state.template==='modern'){var grd=ctx.createLinearGradient(0,0,1600,1132);grd.addColorStop(0,cp);grd.addColorStop(1,'#151222');ctx.fillStyle=grd;ctx.fillRect(0,0,1600,1132);ctx.strokeStyle=ca;ctx.lineWidth=3;ctx.strokeRect(42,42,1516,1048)}else if(state.template==='editorial'){ctx.fillStyle='#f6f0e7';ctx.fillRect(0,0,1600,1132);ctx.fillStyle=ca;ctx.fillRect(55,0,24,1132)}else{ctx.fillStyle=state.template==='classic'?'#fffaf0':'#ffffff';ctx.fillRect(0,0,1600,1132);ctx.strokeStyle=state.template==='minimal'?'#dddddf':ca;ctx.lineWidth=state.template==='minimal'?18:3;ctx.strokeRect(45,45,1510,1042)}
    var light=state.template==='modern',base=light?'#ffffff':'#211b28',muted=light?'#c9c4d0':'#766f79',align=state.template==='editorial'?'left':'center',x=state.template==='editorial'?180:800;
    ctx.fillStyle=light?ca:cp;ctx.beginPath();ctx.arc(x,150,45,0,Math.PI*2);ctx.fill();txt(initialsAward,x,164,31,'Arial',light?'#171222':'#ffffff','center','700');txt((award.name||'AWARD').toUpperCase(),x,250,19,'Arial',light?'#d4cde2':'#675f70',align,'700');txt(state.title,x,340,58,state.template==='modern'||state.template==='minimal'?'Arial':'Georgia',base,align,state.template==='modern'||state.template==='minimal'?'700':'400');txt('This certificate is proudly presented to',x,405,20,'Arial',muted,align,'400');txt(r.name,x,495,54,state.template==='modern'||state.template==='minimal'?'Arial':'Georgia',light?ca:cp,align,'700');txt(awardLabel(r.award).toUpperCase(),x,555,18,'Arial',light?'#ffffff':'#4a3610',align,'800');txt(r.category,x,610,27,'Arial',base,align,'700');wrap(state.copy,state.template==='editorial'?610:800,680,state.template==='editorial'?850:940,31,20,'Arial',muted);
    var sy=910;ctx.strokeStyle=light?'#746d81':'#b8b2ba';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(state.template==='editorial'?180:240,sy);ctx.lineTo(state.template==='editorial'?480:550,sy);ctx.moveTo(state.template==='editorial'?1030:1050,sy);ctx.lineTo(state.template==='editorial'?1360:1360,sy);ctx.stroke();txt(state.signatureOneName,state.template==='editorial'?180:395,sy+32,17,'Arial',base,state.template==='editorial'?'left':'center','700');txt(state.signatureOneTitle,state.template==='editorial'?180:395,sy+56,14,'Arial',muted,state.template==='editorial'?'left':'center','400');txt(state.signatureTwoName,state.template==='editorial'?1030:1205,sy+32,17,'Arial',base,state.template==='editorial'?'left':'center','700');txt(state.signatureTwoTitle,state.template==='editorial'?1030:1205,sy+56,14,'Arial',muted,state.template==='editorial'?'left':'center','400');if(state.verification){drawExportMatrix(ctx,g.code,730,850,140);txt(g.code,800,1017,14,'Arial',muted,'center','700');txt('Verify: certificate-verify.html',800,1040,12,'Arial',muted,'center','400')}txt('Issued '+dateLabel(state.issueDate),state.template==='editorial'?180:800,1080,13,'Arial',muted,state.template==='editorial'?'left':'center','400');var a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=(r.name+'-'+r.category+'-certificate.png').replace(/[^a-z0-9._-]+/gi,'-');a.click();renderAll();toast('Certificate PNG downloaded')}
  function drawExportMatrix(ctx,text,x,y,size){var n=21,cell=size/n,seed=Math.abs(hash(text));ctx.fillStyle='#fff';ctx.fillRect(x,y,size,size);function finder(xx,yy){ctx.fillStyle='#111';ctx.fillRect(x+xx*cell,y+yy*cell,7*cell,7*cell);ctx.fillStyle='#fff';ctx.fillRect(x+(xx+1)*cell,y+(yy+1)*cell,5*cell,5*cell);ctx.fillStyle='#111';ctx.fillRect(x+(xx+2)*cell,y+(yy+2)*cell,3*cell,3*cell)}finder(0,0);finder(14,0);finder(0,14);for(var yy=0;yy<n;yy++){for(var xx=0;xx<n;xx++){if((xx<8&&yy<8)||(xx>12&&yy<8)||(xx<8&&yy>12))continue;seed=(seed*1664525+1013904223)>>>0;if(((seed>>>28)&1)===1){ctx.fillStyle='#111';ctx.fillRect(x+xx*cell,y+yy*cell,Math.ceil(cell),Math.ceil(cell))}}}}
  function openVerify(r){if(!r){toast('No recipient selected');return}if(!state.generated[r.id]){generateRecipient(r);save(false)}var code=state.generated[r.id].code;window.open('certificate-verify.html?id='+encodeURIComponent(code),'_blank')}
  function exportCsv(){var rows=[['Certificate ID','Recipient','Award level','Category','Issue date','Email','Delivery status']];eligible().forEach(function(r){var g=state.generated[r.id];rows.push([g?g.code:'',r.name,awardLabel(r.award),r.category,g?g.issueDate:'',r.email,g?(g.delivery||'ready'):'Not generated'])});var csv=rows.map(function(row){return row.map(function(v){return '"'+String(v||'').replace(/"/g,'""')+'"'}).join(',')}).join('\n');var blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='etb2b_awards-certificates.csv';a.click();setTimeout(function(){URL.revokeObjectURL(url)},600);toast('Certificate register exported')}
  function prepareDelivery(){var gen=eligible().filter(function(r){return state.generated[r.id]});if(!gen.length){toast('Generate at least one certificate first');return}if(!state.emailDelivery){toast('Enable winner email delivery first');return}gen.forEach(function(r){state.generated[r.id].delivery='queued'});state.deliveryPrepared=true;save(false);renderAll();toast(gen.length+' personalized winner email'+(gen.length===1?'':'s')+' prepared')}
  function openLayer(id){var el=document.getElementById(id);if(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}}function closeLayer(id){var el=document.getElementById(id);if(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}}
  function fileToDataUrl(file,cb){if(!file)return;var reader=new FileReader();reader.onload=function(){cb(reader.result)};reader.readAsDataURL(file)}

  load();syncBrandKit(true);$('#sideAwardName').textContent=award.name;$('#crumbAwardName').textContent=award.name;renderAll();
  $$('#templateGrid [data-template]').forEach(function(b){b.addEventListener('click',function(){state.template=b.dataset.template;renderControls();renderPreview();renderHealth()})});
  ['primaryColor','accentColor','certificateTitle','certificateCopy','signatureOneName','signatureOneTitle','signatureTwoName','signatureTwoTitle','enableVerification','emailDelivery','issueDate'].forEach(function(id){var el=document.getElementById(id);el.addEventListener(el.type==='checkbox'?'change':'input',updateFromInputs)});
  $('#signatureOneFile').addEventListener('change',function(){fileToDataUrl(this.files[0],function(url){state.signatureOneImage=url;renderPreview();toast('Signature image added')})});$('#signatureTwoFile').addEventListener('change',function(){fileToDataUrl(this.files[0],function(url){state.signatureTwoImage=url;renderPreview();toast('Signature image added')})});
  $('#syncBrand').addEventListener('click',function(){syncBrandKit(false);save(false)});$('#saveCertificates').addEventListener('click',function(){updateFromInputs();save(true)});$('#syncRecipients').addEventListener('click',function(){categories=loadWinnerState();var list=eligible();if(list.length&&!findRecipient(activeRecipientId))activeRecipientId=list[0].id;renderAll();toast('Winner decisions synced from Page 12')});
  $('#generateSelected').addEventListener('click',generateSelected);$('#insightAction').addEventListener('click',function(){var list=eligible(),gen=list.filter(function(r){return state.generated[r.id]}).length;if(!list.length){location.href='winners.html'}else if(gen<list.length){generateSelected()}else if(protectedRecipients().length){openLayer('protectedModal')}else prepareDelivery()});
  $('#selectAll').addEventListener('change',function(){var v=this.checked;$$('.recipient-check').forEach(function(c){c.checked=v})});$('#recipientSearch').addEventListener('input',renderRows);$$('[data-filter]').forEach(function(b){b.addEventListener('click',function(){filter=b.dataset.filter;$$('[data-filter]').forEach(function(x){x.classList.toggle('active',x===b)});renderRows()})});
  document.addEventListener('change',function(e){if(e.target.matches('.recipient-check'))renderSelectAllState()});
  document.addEventListener('click',function(e){var p=e.target.closest('[data-preview-recipient]');if(p){activeRecipientId=p.dataset.previewRecipient;renderPreview();document.getElementById('certificateStage').scrollIntoView({behavior:'smooth',block:'center'});return}var d=e.target.closest('[data-download-recipient]');if(d){canvasDownload(findRecipient(d.dataset.downloadRecipient));return}var c=e.target.closest('[data-close]');if(c){closeLayer(c.dataset.close);return}var prompt=e.target.closest('[data-prompt]');if(prompt){var blocked=protectedRecipients(),gen=eligible().filter(function(r){return state.generated[r.id]}).length,total=eligible().length,answers={blocked:blocked.length?blocked.length+' winner record'+(blocked.length===1?' is':'s are')+' blocked. ETB2B Awards is protecting them because a decision is not locked or public-name / brand / consent / jury checks are incomplete.':'No winner records are blocked.',copy:'Keep certificate copy short and durable. A strong default is: “In recognition of outstanding achievement, measurable impact and contribution to the future of the industry.” Avoid claims that were not explicitly approved by the jury.',design:'Classic Gold works well for formal industry awards. Modern works for technology-led programs. Minimal is safest when multiple sponsor logos are involved. Editorial is strongest when the brand wants a distinctive premium look.',send:gen+' of '+total+' eligible certificates are generated. '+(state.verification?'Verification is enabled. ':'Verification is currently off. ')+(state.emailDelivery?'Winner email delivery is enabled.':'Email delivery is off.')};$('#copilotAnswer').textContent=answers[prompt.dataset.prompt]||'Your certificate setup is ready for review.';return}});
  $('#downloadCurrent').addEventListener('click',function(){canvasDownload(selectedRecipient())});$('#openCurrentVerify').addEventListener('click',function(){openVerify(selectedRecipient())});$('#previewVerify').addEventListener('click',function(){window.open('certificate-verify.html','_blank')});$('#printCurrent').addEventListener('click',function(){toast('Use Download PNG for a clean asset. Browser print is available from the verification view in production.')});$('#exportCertificates').addEventListener('click',exportCsv);$('#prepareDelivery').addEventListener('click',prepareDelivery);$('#reviewProtected').addEventListener('click',function(){renderProtected();openLayer('protectedModal')});
  $('#openCopilot').addEventListener('click',function(){openLayer('copilotPanel')});$('#openInsightCopilot').addEventListener('click',function(){openLayer('copilotPanel');$('#copilotAnswer').textContent='Your current issuance readiness is '+renderHealth()+'%. Generate all eligible recipients, keep verification on, and review one downloaded sample before preparing delivery.'});
  $$('#zoomSegment [data-zoom]').forEach(function(b){b.addEventListener('click',function(){$$('#zoomSegment [data-zoom]').forEach(function(x){x.classList.toggle('active',x===b)});var root=$('#certificatePreview');if(b.dataset.zoom==='100'){root.style.width='880px';toast('Certificate preview set to 100%')}else{root.style.width='min(880px,100%)'}})});
})();
