(() => {
  const JUDGE_KEY='etb2b_awards_judges_v3', SESSION_KEY='etb2b_jury_session_v1', LEVEL_KEY='etb2b_awards_jury_levels_v1', SCORE_KEY='etb2b_awards_scoring_v11', REVIEW_KEY='etb2b_jury_reviews_v1', NOM_KEY='etb2b_awards_nominations_v1', ASSIGN_KEY='etb2b_awards_jury_assignments_v1', PROGRESS_KEY='etb2b_awards_jury_progress_v1';
  const $=s=>document.querySelector(s), read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}};
  const session=read(SESSION_KEY,null), judges=read(JUDGE_KEY,[]), jury=session&&judges.find(j=>String(j.id)===String(session.juryId));
  if(!jury||jury.enabled===false){window.location.replace('jury-login.html');return}
  const levels=read(LEVEL_KEY,[]), levelNo=Number(jury.level||1), level=levels.find(x=>Number(x.level)===levelNo)||{name:`Jury Level ${levelNo}`,type:'evaluation',categories:jury.categories||[]};
  const nominations=read(NOM_KEY,[]), assignments=read(ASSIGN_KEY,{}), scoring=read(SCORE_KEY,null), progress=read(PROGRESS_KEY,{});
  const criteria=scoring?.criteria?.length?scoring.criteria:[{id:1,name:'Innovation',description:'Originality and differentiation',weight:30,scale:10},{id:2,name:'Market Impact',description:'Customer and industry impact',weight:25,scale:10},{id:3,name:'Execution',description:'Quality of implementation',weight:25,scale:10},{id:4,name:'Scalability',description:'Potential for sustainable growth',weight:20,scale:10}];
  let reviews=read(REVIEW_KEY,{}), currentEntry=null;
  const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  function entries(){const map=assignments[String(levelNo)]||{}, promoted=Number(levelNo)===1?null:new Set(progress[`level${levelNo}_ids`]||[]);return nominations.filter(n=>n.submission==='Submitted'&&n.payment==='Paid'&&(map[n.id]||[]).map(String).includes(String(jury.id))&&(!promoted||promoted.has(n.id))).map(n=>({id:n.id,category:n.category,name:n.nominee||n.company,company:n.company,code:n.id}))}
  function key(e){return `${jury.id}:${e.id}`}
  function render(){
    const es=entries(),submitted=es.filter(e=>reviews[key(e)]?.status==='submitted').length;
    $('#juryWelcome').textContent=jury.name;$('#juryMeta').textContent=`${jury.role||'Jury Member'} · ${jury.company||'Independent'}`;$('#juryLevelPill').textContent=level.name||`Jury Level ${levelNo}`;$('#roundPurpose').textContent=level.type==='verification'?'Verification / eligibility':level.type==='final'?'Final jury decision':'Evaluation / scoring';
    $('#assignedStat').textContent=es.length;$('#submittedStat').textContent=submitted;$('#pendingStat').textContent=es.length-submitted;$('#categoriesStat').textContent=new Set(es.map(e=>e.category)).size;
    $('#juryEntries').innerHTML=es.length?es.map(e=>{const r=reviews[key(e)];return `<article class="entry"><div><small>${esc(e.category)}</small><h3>${esc(e.name)}</h3><p><b>${esc(e.code)}</b> · ${esc(e.company||'')} · ${r?.status==='submitted'?'Evaluation submitted':r?'Draft saved':'Assigned to you'}</p></div>${r?.status==='submitted'?`<span class="done">✓ Submitted · ${Number(r.total||0).toFixed(1)}/10</span>`:`<button data-review="${esc(e.id)}">${r?'Continue':'Review entry'} →</button>`}</article>`}).join(''):'<div class="empty">No nominations are assigned to your account at this jury level.</div>';
  }
  function openScore(id){currentEntry=entries().find(e=>e.id===id);if(!currentEntry)return;const prev=reviews[key(currentEntry)]||{scores:{},comments:''};$('#scoreCategory').textContent=`${currentEntry.category} · ${currentEntry.code}`;$('#scoreTitle').textContent=currentEntry.name;$('#juryComments').value=prev.comments||'';$('#criteriaList').innerHTML=criteria.map(c=>`<div class="criterion"><div><b>${esc(c.name)} · ${Number(c.weight||0)}%</b><small>${esc(c.description||'')}</small></div><input type="number" min="0" max="${Number(c.scale||10)}" step="0.5" value="${prev.scores?.[c.id]??''}" data-criterion="${c.id}" data-scale="${Number(c.scale||10)}" placeholder="/${Number(c.scale||10)}"></div>`).join('');$('#scoreModal').classList.add('open')}
  function save(status){if(!currentEntry)return;const scores={};let valid=true;document.querySelectorAll('[data-criterion]').forEach(i=>{if(i.value===''){if(status==='submitted')valid=false;return}scores[i.dataset.criterion]=Number(i.value)});if(!valid){alert('Please score every criterion before submitting.');return}let total=0;criteria.forEach(c=>{const raw=Number(scores[c.id]??0),scale=Number(c.scale||10);total+=(raw/scale)*(Number(c.weight||0)/100)*10});reviews[key(currentEntry)]={status,scores,comments:$('#juryComments').value.trim(),total,updatedAt:new Date().toISOString(),nominationId:currentEntry.id,level:levelNo};localStorage.setItem(REVIEW_KEY,JSON.stringify(reviews));$('#scoreModal').classList.remove('open');render()}
  $('#juryEntries').addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(b)openScore(b.dataset.review)});$('#closeScore').addEventListener('click',()=>$('#scoreModal').classList.remove('open'));$('#saveDraftScore').addEventListener('click',()=>save('draft'));$('#submitScore').addEventListener('click',()=>save('submitted'));$('#juryLogout').addEventListener('click',()=>{localStorage.removeItem(SESSION_KEY);location.href='jury-login.html'});$('#scoringGuide').addEventListener('click',()=>alert(criteria.map(c=>`${c.name}: ${c.weight}%`).join('\n')));$('#conflictsHelp').addEventListener('click',()=>alert('If you have a conflict of interest with an assigned nomination, contact the award administrator before reviewing it.'));
  render();
})();
