(function(){
  const page=document.body.dataset.nominationPage;if(!page)return;const ctx=window.ETB2BPublicContext||{};const award=ctx.award||{};const slug=ctx.slug||award.slug||'demo';
  const catKey='etb2b_awards_categories_'+slug,settingsKey='etb2b_awards_category_settings_'+slug,selectionKey='etb2b_public_category_selection_'+slug,bucketKey='etb2b_public_nomination_bucket_'+slug,formKey='etb2b_awards_entry_form_'+slug,profileKey='etb2b_public_nominee_profile_'+slug,sharedKey='etb2b_public_shared_answers_'+slug,paymentKey='etb2b_public_payment_'+slug;
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));const symbols={INR:'₹',USD:'$',AED:'د.إ',GBP:'£',SGD:'S$'};const sym=symbols[award.currency]||'₹';const baseFee=award.entryType==='free'?0:Number(award.baseFee||0);const money=n=>Number(n||0)===0?'Free':sym+Number(n||0).toLocaleString('en-IN');
  const settings=read(settingsKey,{selectionMode:'multiple',maxSelections:5,autoImportAnswers:true,aiFinder:true}),cats=read(catKey,[]),form=read(formKey,{title:'Nomination form',intro:'Tell us what makes your work exceptional.',fields:[]});let selected=read(selectionKey,[]).map(String),bucket=read(bucketKey,{items:[]}),profile=read(profileKey,{name:'',email:'',company:'',mobile:''}),shared=read(sharedKey,{});
  if(!form.fields||!form.fields.length)form.fields=[{id:'q1',type:'short',label:'Contact name',required:true,visibility:'all'},{id:'q2',type:'short',label:'Work email',required:true,visibility:'all'},{id:'q3',type:'short',label:'Organisation name',required:true,visibility:'all'},{id:'q4',type:'long',label:'Executive summary',required:true,visibility:'all',limit:300,limitUnit:'words'},{id:'q5',type:'long',label:'Impact & measurable results',required:true,visibility:'all',limit:500,limitUnit:'words'}];
  function read(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?d:x}catch(e){return d}}function write(k,v){localStorage.setItem(k,JSON.stringify(v))}function toast(msg){const t=document.getElementById('publicToast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
  function cat(id){return cats.find(c=>String(c.id)===String(id))||bucket.items?.find(x=>String(x.categoryId)===String(id))||{id,name:'Category',fee:baseFee}}
  function catFee(c){return c.feeMode==='custom'?Number(c.fee||0):Number(c.fee??baseFee)}
  function semantic(f){return String(f.label||f.id||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
  function visibleFields(catId){return (form.fields||[]).filter(f=>f.visibility!=='selected'||!(f.categories||[]).length||(f.categories||[]).map(String).includes(String(catId)))}
  function answerKey(catId){return 'etb2b_public_nomination_answers_'+slug+'_'+catId}
  function syncBucket(){const prior=Array.isArray(bucket.items)?bucket.items:[];bucket={award:award.name,slug,updatedAt:new Date().toISOString(),items:selected.map(id=>{const c=cat(id),p=prior.find(x=>String(x.categoryId)===String(id))||{};const saved=read(answerKey(id),{});return {categoryId:String(id),name:c.name||p.name||'Category',group:c.group||p.group||'',fee:catFee(c),status:saved.completed?'Form complete':(saved.answers&&Object.keys(saved.answers).length?'Draft saved':'Form not started'),completed:!!saved.completed}})};write(bucketKey,bucket);return bucket}
  function updateFooter(){document.querySelectorAll('#footerAward').forEach(x=>x.textContent='© '+new Date().getFullYear()+' '+(award.name||'ETB2B Awards'))}
  updateFooter();syncBucket();
  if(page==='bucket')initBucket();if(page==='form')initForm();if(page==='checkout')initCheckout();if(page==='success')initSuccess();
  function initBucket(){
    if(!selected.length){location.href='nominate.html';return}const ids={name:'profileName',email:'profileEmail',company:'profileCompany',mobile:'profileMobile'};Object.entries(ids).forEach(([k,id])=>{const el=document.getElementById(id);el.value=profile[k]||'';el.addEventListener('input',()=>{profile[k]=el.value;write(profileKey,profile)})});const common=(form.fields||[]).filter(f=>f.type!=='section'&&f.visibility!=='selected').length;document.getElementById('sharedAnswersText').textContent=settings.autoImportAnswers===false?'Answer reuse has been disabled by the award organiser.':('There are '+common+' shared questions that can carry across your selected categories automatically.');if(settings.autoImportAnswers===false)document.getElementById('sharedAnswersBanner').style.opacity='.65';renderBucket();
    document.getElementById('proceedPayment').addEventListener('click',()=>{bucket=syncBucket();if(!bucket.items.every(x=>x.completed)){toast('Complete all nomination forms first');return}location.href='payment-checkout.html'})
  }
  function renderBucket(){bucket=syncBucket();document.getElementById('bucketCount').textContent=bucket.items.length+' categor'+(bucket.items.length===1?'y':'ies');const list=document.getElementById('bucketList');list.innerHTML=bucket.items.map((x,i)=>`<article class="nom-bucket-row"><span class="nom-bucket-num">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(x.name)} <span class="nom-status ${x.completed?'complete':''}">${x.completed?'FORM COMPLETE':x.status.toUpperCase()}</span></h3><p>${esc(x.group||'Award category')}${settings.autoImportAnswers!==false?' · Shared answers will be reused':''}</p></div><div class="nom-bucket-fee">${money(x.fee)}</div><div class="nom-row-action"><a href="nomination-form.html?category=${encodeURIComponent(x.categoryId)}">${x.completed?'Review form':'Fill form'} →</a>${bucket.items.length>1?`<button type="button" data-remove-cat="${esc(x.categoryId)}">Remove</button>`:''}</div></article>`).join('');list.querySelectorAll('[data-remove-cat]').forEach(b=>b.addEventListener('click',()=>{selected=selected.filter(id=>id!==b.dataset.removeCat);write(selectionKey,selected);renderBucket()}));const done=bucket.items.every(x=>x.completed);const btn=document.getElementById('proceedPayment');btn.disabled=!done;btn.textContent=done?'Proceed to payment →':'Complete forms to continue'}
  function initForm(){
    const catId=new URLSearchParams(location.search).get('category')||selected[0];if(!catId||!selected.includes(String(catId))){location.href='nomination-bucket.html';return}const c=cat(catId),fields=visibleFields(catId);document.title=(c.name||'Nomination')+' · ETB2B Awards';document.getElementById('formCategoryGroup').textContent=(c.group||'NOMINATION FORM').toUpperCase();document.getElementById('formCategoryTitle').textContent=c.name||'Category nomination';document.getElementById('sideCategoryName').textContent=c.name||'Category';document.getElementById('publicFormTitle').textContent=form.title||'Nomination form';document.getElementById('publicFormIntro').textContent=form.intro||'';const req=fields.filter(f=>f.type!=='section'&&f.required).length;document.getElementById('sideRequiredCount').textContent=req;document.getElementById('sideOtherCount').textContent=Math.max(0,selected.length-1);document.getElementById('formQuestionCount').textContent=fields.filter(f=>f.type!=='section').length+' questions';let saved=read(answerKey(catId),{answers:{}});saved.answers=saved.answers||{};let imported=0;
    const profileMap={'contact name':profile.name,'your name':profile.name,'work email':profile.email,'email':profile.email,'organisation name':profile.company,'organization name':profile.company,'company name':profile.company,'mobile':profile.mobile,'phone':profile.mobile};
    const values={};fields.forEach(f=>{if(f.type==='section')return;const key=semantic(f);if(saved.answers[key]!=null&&saved.answers[key]!=="")values[key]=saved.answers[key];else if(settings.autoImportAnswers!==false&&shared[key]?.value!=null&&shared[key].value!==""){values[key]=shared[key].value;imported++}else if(profileMap[key]){values[key]=profileMap[key];if(profileMap[key])imported++}});renderFields(fields,values,imported);document.getElementById('sideImportedCount').textContent=imported;if(imported){const banner=document.getElementById('importBanner');banner.hidden=false;document.getElementById('importBannerTitle').textContent=imported+' shared answer'+(imported===1?'':'s')+' imported';document.getElementById('importBannerText').textContent='We reused matching answers from your profile or another nomination. Review before saving.'}
    document.getElementById('saveDraftBtn').addEventListener('click',()=>saveForm(false));document.getElementById('saveNextBtn').addEventListener('click',()=>saveForm(true));document.getElementById('nominationFields').addEventListener('input',updateConditional);document.getElementById('nominationFields').addEventListener('change',updateConditional);updateConditional();
    function renderFields(fs,vals,importCount){const box=document.getElementById('nominationFields');box.innerHTML=fs.map(f=>fieldHtml(f,vals[semantic(f)],!!(vals[semantic(f)]&&saved.answers[semantic(f)]==null))).join('')}
    function fieldHtml(f,val,wasImported){if(f.type==='section')return `<div class="nom-form-section"><h3>${esc(f.label)}</h3><p>${esc(f.help||'')}</p></div>`;const key=semantic(f),req=f.required?'<span class="nom-required"> *</span>':'',badge=wasImported?'<span class="nom-imported">✓ imported</span>':'';let control='';if(f.type==='long')control=`<textarea data-field-key="${esc(key)}" data-field-id="${esc(f.id)}" placeholder="Type your answer...">${esc(val||'')}</textarea>`;else if(f.type==='single')control=`<div class="nom-field-options">${(f.options||[]).map(o=>`<label><input type="radio" data-field-key="${esc(key)}" data-field-id="${esc(f.id)}" name="${esc(key)}" value="${esc(o)}" ${String(val)===String(o)?'checked':''}> ${esc(o)}</label>`).join('')}</div>`;else if(f.type==='multi'){const arr=Array.isArray(val)?val:[];control=`<div class="nom-field-options">${(f.options||[]).map(o=>`<label><input type="checkbox" data-field-key="${esc(key)}" data-field-id="${esc(f.id)}" value="${esc(o)}" ${arr.includes(o)?'checked':''}> ${esc(o)}</label>`).join('')}</div>`}else if(f.type==='file')control=`<div class="nom-file-fake"><input type="file" data-field-key="${esc(key)}" data-field-id="${esc(f.id)}"><small>${esc(val?('Previously selected: '+val):(f.fileTypes||'Upload supporting file'))}</small></div>`;else if(f.type==='number')control=`<input type="number" data-field-key="${esc(key)}" data-field-id="${esc(f.id)}" value="${esc(val||'')}" placeholder="0">`;else control=`<input type="${f.type==='url'?'url':'text'}" data-field-key="${esc(key)}" data-field-id="${esc(f.id)}" value="${esc(val||'')}" placeholder="${f.type==='url'?'https://':'Type your answer...'}">`;return `<div class="nom-field" data-wrap-field-id="${esc(f.id)}"><label>${esc(f.label)}${req}${badge}</label>${f.help?`<small>${esc(f.help)}</small>`:''}${control}${f.limit?`<small>Maximum ${esc(f.limit)} ${esc(f.limitUnit||'characters')}</small>`:''}</div>`}
    function collect(){const answers={};fields.filter(f=>f.type!=='section').forEach(f=>{const key=semantic(f),els=[...document.querySelectorAll(`[data-field-key="${CSS.escape(key)}"]`)];if(f.type==='multi')answers[key]=els.filter(x=>x.checked).map(x=>x.value);else if(f.type==='single')answers[key]=(els.find(x=>x.checked)||{}).value||'';else if(f.type==='file')answers[key]=els[0]?.files?.[0]?.name||saved.answers[key]||'';else answers[key]=els[0]?.value?.trim?.()??''});return answers}
    function validate(answers){let ok=true;fields.filter(f=>f.type!=='section'&&f.required).forEach(f=>{const key=semantic(f),v=answers[key],empty=Array.isArray(v)?!v.length:!String(v||'').trim();const wrap=document.querySelector(`[data-wrap-field-id="${CSS.escape(String(f.id))}"]`);if(wrap)wrap.querySelectorAll('input,textarea,select,.nom-field-options').forEach(x=>x.classList.toggle('nom-error',empty));if(empty)ok=false});return ok}
    function saveForm(complete){const answers=collect();if(complete&&!validate(answers)){toast('Complete the required questions');return}saved={categoryId:String(catId),answers,completed:complete,updatedAt:new Date().toISOString()};write(answerKey(catId),saved);if(settings.autoImportAnswers!==false){fields.filter(f=>f.type!=='section'&&f.type!=='file').forEach(f=>{const key=semantic(f),v=answers[key];if((Array.isArray(v)&&v.length)||(!Array.isArray(v)&&String(v||'').trim()))shared[key]={label:f.label,value:v,sourceCategoryId:String(catId),updatedAt:new Date().toISOString()};});write(sharedKey,shared)}syncBucket();toast(complete?'Nomination form completed':'Draft saved');if(complete){const next=selected.find(id=>id!==String(catId)&&!read(answerKey(id),{}).completed);setTimeout(()=>{location.href=next?'nomination-form.html?category='+encodeURIComponent(next):'nomination-bucket.html'},550)}}
    function updateConditional(){const current=collect();fields.forEach(f=>{if(!f.logic||!f.logic.enabled||!f.logic.fieldId)return;const source=fields.find(x=>String(x.id)===String(f.logic.fieldId));if(!source)return;const sv=current[semantic(source)],target=document.querySelector(`[data-wrap-field-id="${CSS.escape(String(f.id))}"]`);if(!target)return;const wanted=String(f.logic.value||''),actual=Array.isArray(sv)?sv.join(','):String(sv||'');let show=true;if(f.logic.operator==='equals')show=actual===wanted;else if(f.logic.operator==='contains')show=actual.toLowerCase().includes(wanted.toLowerCase());else if(f.logic.operator==='not_equals')show=actual!==wanted;target.hidden=!show})}
  }
  function initCheckout(){bucket=syncBucket();if(!bucket.items.length||!bucket.items.every(x=>x.completed)){location.href='nomination-bucket.html';return}document.getElementById('checkoutCount').textContent=bucket.items.length+' categor'+(bucket.items.length===1?'y':'ies');document.getElementById('checkoutList').innerHTML=bucket.items.map(x=>`<div class="checkout-item"><div><b>${esc(x.name)}</b><small style="display:block;color:#777;font-size:8px;margin-top:3px">Form complete</small></div><span>${money(x.fee)}</span></div>`).join('');const subtotal=bucket.items.reduce((n,x)=>n+Number(x.fee||0),0),taxPercent=Number(award.taxPercent??18),tax=subtotal>0?Math.round(subtotal*taxPercent/100):0,grand=subtotal+tax;document.getElementById('checkoutSubtotal').textContent=money(subtotal);document.getElementById('checkoutTax').textContent=subtotal?money(tax)+' ('+taxPercent+'%)':money(0);document.getElementById('checkoutGrand').textContent=money(grand);let method='Card';document.querySelectorAll('[data-method]').forEach(b=>b.addEventListener('click',()=>{method=b.dataset.method;document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('active',x===b))}));const btn=document.getElementById('paySubmitBtn');if(grand===0)btn.textContent='Submit nominations';btn.addEventListener('click',()=>{btn.disabled=true;btn.textContent=grand?'Processing demo payment…':'Submitting…';const payment={id:'ETPAY-'+Date.now().toString().slice(-8),award:award.name,slug,amount:grand,subtotal,tax,method,status:'Paid',createdAt:new Date().toISOString(),categories:bucket.items.map(x=>x.name)};write(paymentKey,payment);const starters=read('etb2b_public_nomination_starters',[]);bucket.items.forEach(x=>{if(!starters.some(s=>s.paymentId===payment.id&&s.category===x.name))starters.push({id:'ET-'+Date.now().toString().slice(-6)+'-'+Math.random().toString(36).slice(2,5),award:award.name,category:x.name,name:profile.company||profile.name||'Entrant',email:profile.email||'',status:'Submitted',paymentId:payment.id,amount:x.fee,createdAt:new Date().toISOString()})});write('etb2b_public_nomination_starters',starters);bucket.items=bucket.items.map(x=>Object.assign({},x,{status:'Submitted',submitted:true,paymentId:payment.id}));write(bucketKey,bucket);setTimeout(()=>location.href='nomination-success.html',700)})}
  function initSuccess(){const payment=read(paymentKey,null);const count=(bucket.items||[]).length;document.getElementById('successText').textContent=payment?count+' nomination'+(count===1?'':'s')+' submitted successfully. Confirmation '+payment.id+' · '+money(payment.amount)+'.':count+' nomination'+(count===1?'':'s')+' submitted successfully.'}
})();
