(function(){
  const ctx=window.ETB2BPublicContext;if(!ctx)return;const {state}=ctx;const pageId=document.body.dataset.page||'';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const page=(state.publicPages||[]).find(p=>p.id===pageId);
  const pairs=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf('|');return i<0?[line,'']:[line.slice(0,i).trim(),line.slice(i+1).trim()]});
  function setHero(){if(!page)return;const hero=document.querySelector('.info-hero');if(hero){const k=hero.querySelector('.pp-kicker'),h=hero.querySelector('h1'),p=hero.querySelector('p');if(k)k.textContent=page.eyebrow||page.label;if(h)h.textContent=page.title||page.label;if(p)p.textContent=page.intro||''}document.title=(page.title||page.label)+' · ETB2B Awards'}
  if(page&&page.enabled===false){const main=document.querySelector('.pp-main');if(main)main.innerHTML=`<section class="info-hero"><span class="pp-kicker">PAGE OFFLINE</span><h1>${esc(page.label)}</h1><p>This page is currently disabled in Website Studio.</p></section>`;return}
  setHero();
  const jury=document.getElementById('juryGrid');if(jury){const section=(state.sections||[]).find(s=>s.id==='speakers');const speakers=(section?.speakers||[]).filter(x=>x.status!==false);jury.innerHTML=speakers.length?speakers.map(s=>`<article class="jury-card"><div class="jury-avatar">${s.photo?`<img src="${esc(s.photo)}" alt="${esc(s.name)}">`:esc((s.name||'J').split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div><b>${esc(s.name)}</b><span>${esc(s.role||'Jury Member')}</span><span>${esc(s.company||'')}</span></div></article>`).join(''):'<article class="info-card"><h3>Jury details coming soon</h3><p>The judging panel will be announced here.</p></article>'}
  const criteria=document.getElementById('criteriaList');if(criteria){let sc=null;try{sc=JSON.parse(localStorage.getItem('etb2b_awards_scoring_v11')||'null')}catch(e){}const rows=sc?.criteria?.length?sc.criteria:[{name:'Innovation',description:'Originality, differentiation and quality of the solution or idea.',weight:30},{name:'Market Impact',description:'Business, customer, industry or societal outcomes demonstrated by the entry.',weight:30},{name:'Execution',description:'Quality of implementation, craft, delivery and operational excellence.',weight:20},{name:'Scalability',description:'Potential for sustainable growth, repeatability and long-term value.',weight:20}];criteria.innerHTML=rows.map((c,i)=>`<article class="criterion-row"><div class="criterion-number">0${i+1}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.description||'')}</p></div><div class="criterion-weight">${Number(c.weight||0)}%</div></article>`).join('')+(page?.note?`<article class="criteria-note"><b>Judging note</b><p>${esc(page.note)}</p></article>`:'')}
  const contacts=document.getElementById('contactDirectory');if(contacts){const section=(state.sections||[]).find(s=>s.id==='contact');const rows=(section?.contacts||[]).filter(x=>x.status!==false);const escalation=section?.escalationText||'For any issues requiring immediate escalation, please write to shahbaz.khan@timesinternet.in - Md. Shahbaz Khan, Head of Special Initiatives & Business Strategy, The Economic Times Business Verticals.';contacts.innerHTML=(rows.length?rows:[{name:'Awards Helpdesk',designation:'Awards Team',company:'ETB2B Awards',email:section?.email||'awards@etb2b.com',phone:section?.phone||'+91 98765 43210'}]).map(c=>`<article><h3>${esc(c.name)}</h3>${c.designation?`<p>${esc(c.designation)}</p>`:''}${c.company?`<p>${esc(c.company)}</p>`:''}${c.email?`<a href="mailto:${esc(c.email)}">${esc(c.email)}</a>`:''}${c.phone?`<a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:''}</article>`).join('')+`<div class="contact-page-escalation">${esc(escalation)}</div>`}
  if(pageId==='guidelines'){const host=document.querySelector('.guideline-steps');if(host&&page)host.innerHTML=pairs(page.items).map((x,i)=>`<article class="guideline-step"><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('')}
  if(pageId==='terms'){const host=document.querySelector('.info-grid');if(host&&page)host.innerHTML=pairs(page.items).map((x,i)=>`<article class="info-card"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('')}
  if(pageId==='faq'){const host=document.querySelector('.faq-list');if(host&&page)host.innerHTML=pairs(page.items).map((x,i)=>`<details ${i===0?'open':''}><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p></details>`).join('')}
  if(pageId==='previous'&&page){const hero=document.querySelector('.previous-hero');if(hero)hero.innerHTML=`<h2>${esc(page.title||'Previous Edition')}</h2><p>${esc(page.body||page.intro||'')}</p>`}
})();
