(function(){
  const ctx=window.ETB2BPublicContext;if(!ctx)return;const {state}=ctx;const pageId=document.body.dataset.page||'';
  const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const page=(state.publicPages||[]).find(p=>p.id===pageId);
  const pairs=v=>String(v||'').split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf('|');return i<0?[line,'']:[line.slice(0,i).trim(),line.slice(i+1).trim()]});
  function setHero(){if(!page)return;const hero=document.querySelector('.info-hero');if(hero){const k=hero.querySelector('.pp-kicker'),h=hero.querySelector('h1'),p=hero.querySelector('p');if(k)k.textContent=page.eyebrow||page.label;if(h)h.textContent=page.title||page.label;if(p)p.textContent=page.intro||''}document.title=(page.title||page.label)+' · ETB2B Awards'}
  if(page&&page.enabled===false){const main=document.querySelector('.pp-main');if(main)main.innerHTML=`<section class="info-hero"><span class="pp-kicker">PAGE OFFLINE</span><h1>${esc(page.label)}</h1><p>This page is currently disabled in Website Studio.</p></section>`;return}
  setHero();
  const jury=document.getElementById('juryGrid');if(jury){const section=(state.sections||[]).find(s=>s.id==='speakers');const speakers=(section?.speakers||[]).filter(x=>x.status!==false);jury.innerHTML=speakers.length?speakers.map(s=>`<article class="jury-card"><div class="jury-avatar">${s.photo?`<img src="${esc(s.photo)}" alt="${esc(s.name)}">`:esc((s.name||'J').split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div><b>${esc(s.name)}</b><span>${esc(s.role||'Jury Member')}</span><span>${esc(s.company||'')}</span></div></article>`).join(''):'<article class="info-card"><h3>Jury details coming soon</h3><p>The judging panel will be announced here.</p></article>'}
  const criteria=document.getElementById('criteriaList');if(criteria){
    let sc=null;try{sc=JSON.parse(localStorage.getItem('etb2b_awards_scoring_v11')||'null')}catch(e){}
    const award=(()=>{try{return JSON.parse(localStorage.getItem('etb2b_awards_new_award')||'null')}catch(e){return null}})()||{},slug=award.slug||'demo';
    let cats=[];try{cats=(JSON.parse(localStorage.getItem('etb2b_awards_categories_'+slug)||'[]')||[]).filter(c=>c&&c.status!=='deleted'&&c.status!=='inactive').map(c=>c.name).filter(Boolean)}catch(e){}
    const rows=sc?.criteria?.length?sc.criteria:[{name:'Innovation',description:'Originality, differentiation and quality of the solution or idea.',weight:30,categories:['All categories']},{name:'Market Impact',description:'Business, customer, industry or societal outcomes demonstrated by the entry.',weight:30,categories:['All categories']},{name:'Execution',description:'Quality of implementation, craft, delivery and operational excellence.',weight:20,categories:['All categories']},{name:'Scalability',description:'Potential for sustainable growth, repeatability and long-term value.',weight:20,categories:['All categories']}];
    if(!cats.length)cats=[...new Set(rows.flatMap(c=>Array.isArray(c.categories)?c.categories:[]).filter(Boolean))];
    if(!cats.length)cats=['All categories'];
    const normalized=rows.map(c=>({...c,categories:Array.isArray(c.categories)&&c.categories.length?c.categories:(c.category&&c.category!=='all'?[c.category]:cats)}));
    const filter=document.getElementById('publicCriteriaCategory'),search=document.getElementById('publicCriteriaSearch');
    if(filter)filter.innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
    const renderCriteria=()=>{const q=(search?.value||'').toLowerCase().trim(),fc=filter?.value||'all';const visible=cats.filter(cat=>fc==='all'||cat===fc).map(cat=>{const cr=normalized.filter(c=>(c.categories||[]).includes(cat)&&(!q||`${cat} ${c.name} ${c.description||''}`.toLowerCase().includes(q)));if(!cr.length)return'';const total=cr.reduce((s,c)=>s+Number(c.weight||0),0);return `<section class="criteria-category-section" data-public-category="${esc(cat)}"><div class="criteria-category-title">${esc(cat)}</div><table class="criteria-public-table"><thead><tr><th>Evaluation Criteria</th><th>Weightage (%)</th></tr></thead><tbody>${cr.map(c=>`<tr><td><b>${esc(c.name)}</b>${c.description?`<span class="criteria-description">${esc(c.description)}</span>`:''}</td><td>${Number(c.weight||0)}%</td></tr>`).join('')}</tbody><tfoot><tr><td>Total</td><td>${total}%</td></tr></tfoot></table></section>`}).join('');criteria.innerHTML=visible||'<div class="criteria-public-empty">No criteria match this view.</div>'+(page?.note?`<article class="criteria-note"><b>Judging note</b><p>${esc(page.note)}</p></article>`:'')};
    search?.addEventListener('input',renderCriteria);filter?.addEventListener('change',renderCriteria);renderCriteria();
  }
  const contacts=document.getElementById('contactDirectory');if(contacts){const section=(state.sections||[]).find(s=>s.id==='contact');const rows=(section?.contacts||[]).filter(x=>x.status!==false);const escalation=section?.escalationText||'For any issues requiring immediate escalation, please write to shahbaz.khan@timesinternet.in - Md. Shahbaz Khan, Head of Special Initiatives & Business Strategy, The Economic Times Business Verticals.';contacts.innerHTML=(rows.length?rows:[{name:'Awards Helpdesk',designation:'Awards Team',company:'ETB2B Awards',email:section?.email||'awards@etb2b.com',phone:section?.phone||'+91 98765 43210'}]).map(c=>`<article><h3>${esc(c.name)}</h3>${c.designation?`<p>${esc(c.designation)}</p>`:''}${c.company?`<p>${esc(c.company)}</p>`:''}${c.email?`<a href="mailto:${esc(c.email)}">${esc(c.email)}</a>`:''}${c.phone?`<a href="tel:${esc(c.phone)}">${esc(c.phone)}</a>`:''}</article>`).join('')+`<div class="contact-page-escalation">${esc(escalation)}</div>`}
  if(pageId==='guidelines'){const host=document.querySelector('.guideline-steps');if(host&&page)host.innerHTML=pairs(page.items).map((x,i)=>`<article class="guideline-step"><span>${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('')}
  if(pageId==='terms'){const host=document.querySelector('.info-grid');if(host&&page)host.innerHTML=pairs(page.items).map((x,i)=>`<article class="info-card"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('')}
  if(pageId==='faq'){const host=document.querySelector('.faq-list');if(host&&page)host.innerHTML=pairs(page.items).map((x,i)=>`<details ${i===0?'open':''}><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p></details>`).join('')}
  if(pageId==='previous'&&page){const hero=document.querySelector('.previous-hero');if(hero)hero.innerHTML=`<h2>${esc(page.title||'Previous Edition')}</h2><p>${esc(page.body||page.intro||'')}</p>`}
})();
