(function(){
  const savedAward=(()=>{try{return JSON.parse(localStorage.getItem('etb2b_awards_new_award')||'null')}catch(e){return null}})();
  const award=savedAward||{name:'India FinTech Awards 2027',description:'Recognising breakthrough founders, products and teams transforming financial technology across India.',industry:'FinTech',slug:'india-fintech-awards-2027',openDate:'2027-06-01',closeDate:'2027-09-30',judgingDate:'2027-10-10',winnerDate:'2027-11-01'};
  const slug=award.slug||String(award.name||'award').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const categoryKey=savedAward&&savedAward.slug?'etb2b_awards_categories_'+savedAward.slug:'etb2b_awards_categories_demo';
  let categories=(()=>{try{return JSON.parse(localStorage.getItem(categoryKey)||'[]')}catch(e){return []}})();
  if(!categories.length)categories=[{name:'Best FinTech Startup',description:'Recognising an ambitious company creating meaningful market impact.'},{name:'Digital Banking Innovation',description:'For products transforming how people and businesses bank.'},{name:'Payments Solution of the Year',description:'Recognising standout payment technology and customer experience.'},{name:'FinTech Leader of the Year',description:'Celebrating exceptional leadership and contribution to the ecosystem.'},{name:'Best AI in Financial Services',description:'For responsible AI creating measurable value in financial services.'},{name:'Financial Inclusion Award',description:'Recognising solutions expanding access to financial services.'}];
  const defaults={template:'modern',primary:'#6258f5',accent:'#17a673',headingFont:'modern',cornerStyle:'soft',stageAuto:true,published:false,publishedAt:'',pages:{categories:true,judges:true,winners:true,sponsors:true,contact:true},content:{heroEyebrow:(award.industry||'Industry')+' awards',heroTitle:'Celebrating the people shaping what comes next.',heroBody:award.description||'Recognising excellence, innovation and measurable impact.',heroCta:'Nominate now',aboutTitle:'Where excellence gets recognised.',aboutBody:'Built to recognise the organisations, teams and leaders setting new standards. Explore the categories, prepare your strongest work and join a community celebrating meaningful achievement.',categoriesTitle:'Find your category',categoriesBody:'Choose the category that best matches your work, impact and ambition.',timelineTitle:'Your path to the awards',timelineBody:'Key dates from entries opening through to the winner announcement.',judgesTitle:'Judged by industry leaders',judgesBody:'Independent experts bring experience, perspective and a consistent scoring framework.',sponsorsTitle:'Supported by our partners',sponsorsBody:'Partners helping us celebrate excellence across the industry.',faqTitle:'Questions before you enter?',faqBody:'Everything you need to know before starting your nomination.',ctaTitle:'Ready to put your work forward?',ctaBody:'Start your entry today. Save progress, collaborate with your team and submit before the deadline.',countdownTitle:'Entries close soon',countdownBody:'Give your team enough time to prepare a strong submission.',statsTitle:'An awards community with impact',statsBody:'A growing platform for ambitious organisations and industry leaders.',testimonialsTitle:'Why people enter',testimonialsBody:'Hear from past participants about the value of taking part.'},sections:[{id:'hero',enabled:true},{id:'about',enabled:true},{id:'categories',enabled:true},{id:'timeline',enabled:true},{id:'judges',enabled:true},{id:'sponsors',enabled:true},{id:'faq',enabled:true},{id:'cta',enabled:true}]};
  let saved=null;try{saved=JSON.parse(localStorage.getItem('etb2b_awards_website_'+slug)||'null')}catch(e){}
  const state=saved?merge(JSON.parse(JSON.stringify(defaults)),saved):defaults;
  function merge(t,s){Object.keys(s||{}).forEach(k=>{if(s[k]&&typeof s[k]==='object'&&!Array.isArray(s[k])&&t[k]&&typeof t[k]==='object'&&!Array.isArray(t[k]))merge(t[k],s[k]);else t[k]=s[k]});return t}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function fmtDate(v){if(!v)return'To be announced';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function initials(name){return String(name||'A').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
  function daysUntilClose(){if(!award.closeDate)return 42;return Math.max(0,Math.ceil((new Date(award.closeDate+'T23:59:59')-new Date())/86400000))}
  function currentStage(){if(!state.stageAuto)return{label:'Entries open',cta:state.content.heroCta||'Nominate now'};const now=new Date(),open=award.openDate?new Date(award.openDate+'T00:00:00'):null,close=award.closeDate?new Date(award.closeDate+'T23:59:59'):null,winner=award.winnerDate?new Date(award.winnerDate+'T00:00:00'):null;if(open&&now<open)return{label:'Opening '+fmtDate(award.openDate),cta:'Get notified'};if(close&&now<=close)return{label:'Entries open',cta:'Nominate now'};if(winner&&now<winner)return{label:'Judging in progress',cta:'View categories'};if(winner&&now>=winner)return{label:'Winners announced',cta:'View winners'};return{label:'Awards programme',cta:state.content.heroCta||'Nominate now'}}
  const stage=currentStage();
  document.title=state.seo&&state.seo.title?state.seo.title:award.name;
  const meta=document.querySelector('meta[name="description"]');if(meta&&state.seo&&state.seo.description)meta.content=state.seo.description;
  const site=document.getElementById('publicSite');site.className='ps-site template-'+state.template+' corner-'+state.cornerStyle+' font-'+state.headingFont;site.style.setProperty('--site-primary',state.primary);site.style.setProperty('--site-accent',state.accent);
  const links=[];if(state.pages.categories)links.push('<a href="#categories">Categories</a>');if(state.pages.judges)links.push('<a href="#judges">Judges</a>');if(state.pages.winners)links.push('<a href="#winners">Winners</a>');if(state.pages.sponsors)links.push('<a href="#sponsors">Sponsors</a>');links.push(`<a href="#" class="ps-primary" data-nominate>${esc(stage.cta)}</a>`);
  let html=`<nav class="ps-nav"><div class="ps-brand"><span class="ps-logo">${esc(initials(award.name))}</span><b>${esc(award.name)}</b></div><div class="ps-links">${links.join('')}</div></nav>`;
  state.sections.filter(s=>s.enabled).forEach((s,i)=>html+=renderSection(s.id,i));
  html+=`<footer class="ps-footer"><span>&copy; ${new Date().getFullYear()} ${esc(award.name)}. All rights reserved.</span><span>Vikas Mishra</span></footer>`;site.innerHTML=html;
  function renderSection(id,i){const c=state.content,alt=i%2?' alt':'';
    if(id==='hero')return `<header class="ps-hero"><div class="ps-hero-inner"><div class="ps-eyebrow">${esc(c.heroEyebrow)} <span class="ps-stage">${esc(stage.label)}</span></div><h1>${esc(c.heroTitle)}</h1><p>${esc(c.heroBody)}</p><div class="ps-hero-actions"><button class="ps-primary" data-nominate>${esc(stage.cta)}</button><a class="ps-secondary-link" href="#about">Explore the awards</a></div></div></header>`;
    if(id==='about')return `<section class="ps-section${alt}" id="about"><span class="ps-kicker">About the awards</span><h2>${esc(c.aboutTitle)}</h2><p class="ps-lead">${esc(c.aboutBody)}</p></section>`;
    if(id==='categories')return `<section class="ps-section${alt}" id="categories"><span class="ps-kicker">Categories</span><h2>${esc(c.categoriesTitle)}</h2><p class="ps-lead">${esc(c.categoriesBody)}</p><div class="ps-category-grid">${categories.slice(0,9).map((cat,j)=>`<article class="ps-category-card"><span>${String(j+1).padStart(2,'0')}</span><h3>${esc(cat.name)}</h3><p>${esc(cat.description||'Recognising exceptional work, innovation and measurable impact.')}</p></article>`).join('')}</div></section>`;
    if(id==='timeline')return `<section class="ps-section${alt}"><span class="ps-kicker">Timeline</span><h2>${esc(c.timelineTitle)}</h2><p class="ps-lead">${esc(c.timelineBody)}</p><div class="ps-timeline"><div class="ps-time"><small>Entries open</small><b>${esc(fmtDate(award.openDate))}</b></div><div class="ps-time"><small>Entry deadline</small><b>${esc(fmtDate(award.closeDate))}</b></div><div class="ps-time"><small>Judging</small><b>${esc(fmtDate(award.judgingDate))}</b></div><div class="ps-time"><small>Winners</small><b>${esc(fmtDate(award.winnerDate))}</b></div></div></section>`;
    if(id==='judges')return `<section class="ps-section${alt}" id="judges"><span class="ps-kicker">Independent jury</span><h2>${esc(c.judgesTitle)}</h2><p class="ps-lead">${esc(c.judgesBody)}</p><div class="ps-judge-grid">${['Aarav Mehta','Maya Kapoor','Rohan Shah','Neha Iyer'].map((n,j)=>`<article class="ps-judge"><div class="ps-avatar"></div><b>${n}</b><small>${['FinTech Investor','Banking Leader','Product Executive','Technology Advisor'][j]}</small></article>`).join('')}</div></section>`;
    if(id==='sponsors')return `<section class="ps-section${alt}" id="sponsors"><span class="ps-kicker">Partners</span><h2>${esc(c.sponsorsTitle)}</h2><p class="ps-lead">${esc(c.sponsorsBody)}</p><div class="ps-sponsors"><span class="ps-sponsor">PARTNER ONE</span><span class="ps-sponsor">PARTNER TWO</span><span class="ps-sponsor">MEDIA PARTNER</span><span class="ps-sponsor">KNOWLEDGE PARTNER</span></div></section>`;
    if(id==='faq')return `<section class="ps-section${alt}"><span class="ps-kicker">FAQ</span><h2>${esc(c.faqTitle)}</h2><p class="ps-lead">${esc(c.faqBody)}</p><div class="ps-faq"><div class="ps-faq-item"><b>Who can enter?</b><p>Eligibility depends on the category. Review the category criteria before starting your submission.</p></div><div class="ps-faq-item"><b>Can I save and return later?</b><p>Yes. Entrants can save a draft and complete the submission before the deadline.</p></div><div class="ps-faq-item"><b>How are entries judged?</b><p>Independent judges score eligible submissions against the published criteria.</p></div></div></section>`;
    if(id==='cta')return `<section class="ps-final"><h2>${esc(c.ctaTitle)}</h2><p>${esc(c.ctaBody)}</p><button class="ps-primary" data-nominate>${esc(stage.cta)}</button></section>`;
    if(id==='countdown')return `<section class="ps-section${alt}"><span class="ps-kicker">Deadline</span><h2>${esc(c.countdownTitle)}</h2><p class="ps-lead">${esc(c.countdownBody)}</p><div class="ps-countdown"><div><b>${esc(fmtDate(award.closeDate))}</b><small>Entry deadline for ${esc(award.name)}</small></div><div><div class="ps-countdown-number">${daysUntilClose()}</div><small>days remaining</small></div></div></section>`;
    if(id==='stats')return `<section class="ps-section${alt}"><span class="ps-kicker">Impact</span><h2>${esc(c.statsTitle)}</h2><p class="ps-lead">${esc(c.statsBody)}</p><div class="ps-stats"><div class="ps-stat"><b>682</b><span>Registrations</span></div><div class="ps-stat"><b>${categories.length}</b><span>Categories</span></div><div class="ps-stat"><b>18</b><span>Industry judges</span></div><div class="ps-stat"><b>11</b><span>Countries reached</span></div></div></section>`;
    if(id==='testimonials')return `<section class="ps-section${alt}"><span class="ps-kicker">Community</span><h2>${esc(c.testimonialsTitle)}</h2><p class="ps-lead">${esc(c.testimonialsBody)}</p><div class="ps-testimonial"><p>Being recognised gave our team credibility with customers, partners and future talent.</p><small>Previous award participant - Demo quote</small></div></section>`;
    return ''}
  const previewBar=document.getElementById('previewBar');document.getElementById('previewStatus').textContent=state.published?'Live website':'Draft website';previewBar.classList.toggle('live',!!state.published);
  const select=document.getElementById('nominateCategory');select.innerHTML=categories.map(c=>`<option>${esc(c.name)}</option>`).join('');
  document.querySelectorAll('[data-nominate]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();document.getElementById('nominateModal').classList.add('open');document.getElementById('nominateModal').setAttribute('aria-hidden','false')}));
  document.querySelectorAll('[data-close-nominate]').forEach(x=>x.addEventListener('click',()=>{document.getElementById('nominateModal').classList.remove('open');document.getElementById('nominateModal').setAttribute('aria-hidden','true')}));
  document.getElementById('nominateTitle').textContent='Enter '+award.name;
  document.getElementById('startEntryBtn').addEventListener('click',()=>{const t=document.getElementById('psToast');t.textContent='Demo: entrant registration would start here';t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);document.getElementById('nominateModal').classList.remove('open')});
})();
