(function(){
  var categories=[
    {id:'startup',name:'Best FinTech Startup',format:'single',locked:false,finalists:[
      {id:'nova',name:'NovaPay Technologies',tag:'Digital-first payment infrastructure',score:91.4,votes:4,totalVotes:5,award:'winner',nameVerified:true,brandVerified:true,consent:false,juryApproved:true,note:''},
      {id:'cred',name:'CredStack',tag:'Embedded credit infrastructure',score:89.7,votes:1,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''},
      {id:'astra',name:'AstraLedger',tag:'SME treasury automation',score:88.4,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:false,consent:true,juryApproved:true,note:''},
      {id:'pulse',name:'PulseCredit',tag:'Alternative underwriting platform',score:87.6,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:false,note:''},
      {id:'finbridge',name:'FinBridge Labs',tag:'Open-finance connectivity',score:86.8,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''}
    ]},
    {id:'lending',name:'Best Digital Lending',format:'single',locked:true,finalists:[
      {id:'clearlend',name:'ClearLend',tag:'Embedded SME credit platform',score:92.1,votes:5,totalVotes:5,award:'winner',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:'Unanimous panel approval.'},
      {id:'creditnova',name:'CreditNova',tag:'Alternative risk engine',score:88.6,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''},
      {id:'lendverse',name:'LendVerse',tag:'Supply-chain lending network',score:86.9,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''}
    ]},
    {id:'payments',name:'Best Payments Innovation',format:'single',locked:true,finalists:[
      {id:'paymesh',name:'PayMesh',tag:'Programmable merchant payments',score:90.8,votes:4,totalVotes:5,award:'winner',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''},
      {id:'tapgrid',name:'TapGrid',tag:'Offline-first acceptance network',score:89.0,votes:1,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''},
      {id:'settly',name:'Settly',tag:'Cross-border settlement layer',score:87.4,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''}
    ]},
    {id:'ai',name:'Best AI in Financial Services',format:'single',locked:false,finalists:[
      {id:'riskmind',name:'RiskMind AI',tag:'Explainable underwriting intelligence',score:90.2,votes:3,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:false,note:''},
      {id:'finpilot',name:'FinPilot Labs',tag:'AI operations copilot for banks',score:89.9,votes:2,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:false,note:''},
      {id:'fraudlens',name:'FraudLens',tag:'Realtime fraud pattern detection',score:87.9,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''}
    ]},
    {id:'leader',name:'FinTech Leader of the Year',format:'single',locked:true,finalists:[
      {id:'neha',name:'Neha Rao - Orbit Finance',tag:'Founder and CEO',score:93.0,votes:5,totalVotes:5,award:'winner',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''},
      {id:'arjun',name:'Arjun Mehta - NovaPay',tag:'Co-founder',score:89.2,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''}
    ]}
  ];
  var activeCategoryId='startup';
  var activeFinalist=null;
  var stateKey='etb2b_awards.winners.v13';
  var packGenerated=false;
  var $=function(s){return document.querySelector(s)};
  var $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
  function toast(msg){var el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__wnToast);window.__wnToast=setTimeout(function(){el.classList.remove('show')},2200)}
  function activeCategory(){return categories.filter(function(c){return c.id===activeCategoryId})[0]||categories[0]}
  function recipientAwards(format){if(format==='medals')return['gold','silver','bronze'];if(format==='winner-runner')return['winner','runner-up'];return['winner']}
  function isRecipient(f,c){return recipientAwards(c.format).indexOf(f.award)>-1}
  function recipientLabel(v){var map={winner:'Winner','runner-up':'Runner-up',gold:'Gold',silver:'Silver',bronze:'Bronze',finalist:'Finalist'};return map[v]||'Finalist'}
  function verificationComplete(f){return f.nameVerified&&f.brandVerified&&f.consent&&f.juryApproved}
  function categoryRecipients(c){return c.finalists.filter(function(f){return isRecipient(f,c)})}
  function awardClass(v){return ['winner','gold','silver','bronze'].indexOf(v)>-1?v:''}
  function optionsFor(format,current){var opts=format==='medals'?[['finalist','Finalist'],['gold','Gold'],['silver','Silver'],['bronze','Bronze']]:format==='winner-runner'?[['finalist','Finalist'],['winner','Winner'],['runner-up','Runner-up']]:[['finalist','Finalist'],['winner','Winner']];return opts.map(function(o){return '<option value="'+o[0]+'" '+(current===o[0]?'selected':'')+'>'+o[1]+'</option>'}).join('')}
  function categoryStatus(c){var rec=categoryRecipients(c);if(c.locked)return{label:'Locked',cls:'locked'};if(!rec.length)return{label:'Winner missing',cls:'issue'};if(rec.some(function(f){return !verificationComplete(f)}))return{label:'Needs verification',cls:'issue'};return{label:'Ready to lock',cls:''}}
  function renderTabs(){var root=$('#categoryTabs');root.innerHTML=categories.map(function(c){var st=categoryStatus(c);return '<button data-category="'+c.id+'" class="'+(c.id===activeCategoryId?'active ':'')+st.cls+'"><b>'+c.name+'</b><span>'+st.label+'</span></button>'}).join('');$$('[data-category]').forEach(function(btn){btn.addEventListener('click',function(){activeCategoryId=this.dataset.category;renderAll();save()})})}
  function renderTable(){var c=activeCategory();$('#activeCategoryTitle').textContent=c.name;$('#awardFormat').value=c.format;$('#awardFormat').disabled=c.locked;$('#lockCategory').textContent=c.locked?'Winner locked':'Lock winner';$('#lockCategory').disabled=c.locked;var body=$('#winnerTableBody');body.innerHTML='';c.finalists.slice().sort(function(a,b){return b.score-a.score}).forEach(function(f,i){var tr=document.createElement('tr');var recipient=isRecipient(f,c);tr.className=(recipient?'recipient ':'')+(c.locked?'locked':'');tr.innerHTML='<td><span class="wn-rank '+(i===0?'top':'')+'">#'+(i+1)+'</span></td><td><div class="wn-finalist-name"><b>'+f.name+'</b><span>'+f.tag+'</span></div></td><td><div class="wn-score"><strong>'+f.score.toFixed(1)+'</strong><small>normalized / 100</small></div></td><td><span class="wn-jury '+(f.juryApproved?'':'warn')+'"><i></i>'+f.votes+'/'+f.totalVotes+' votes</span></td><td><span class="wn-verify '+(verificationComplete(f)?'':'warn')+'">'+(verificationComplete(f)?'Ready':'Check details')+'</span></td><td><select class="wn-award-select '+awardClass(f.award)+'" data-award="'+f.id+'" '+(c.locked?'disabled':'')+'>'+optionsFor(c.format,f.award)+'</select></td><td><button class="wn-row-menu" data-open-finalist="'+f.id+'">...</button></td>';body.appendChild(tr)});bindTable()}
  function bindTable(){$$('[data-award]').forEach(function(sel){sel.addEventListener('change',function(){var c=activeCategory(),f=findFinalist(c,this.dataset.award);if(!f)return;var old=f.award;assignAward(c,f,this.value);addAudit('Award assignment changed',f.name+' changed from '+recipientLabel(old)+' to '+recipientLabel(f.award)+'.','good');save();renderAll();toast('Award assignment updated')})});$$('[data-open-finalist]').forEach(function(btn){btn.addEventListener('click',function(){openFinalist(this.dataset.openFinalist)})})}
  function assignAward(c,f,value){var exclusive=['winner','runner-up','gold','silver','bronze'];if(exclusive.indexOf(value)>-1){c.finalists.forEach(function(other){if(other.id!==f.id&&other.award===value)other.award='finalist'})}f.award=value}
  function findFinalist(c,id){return c.finalists.filter(function(f){return f.id===id})[0]}

  function seedStartupFromShortlist(){try{if(localStorage.getItem(stateKey))return;var s=JSON.parse(localStorage.getItem('etb2b_awards.shortlist.v12')||'null');if(!s||!s.locked||!s.entries)return;var source={1:{id:'nova',name:'NovaPay Technologies',tag:'Digital-first payment infrastructure',score:91.4},2:{id:'cred',name:'CredStack',tag:'Embedded credit infrastructure',score:89.7},3:{id:'astra',name:'AstraLedger',tag:'SME treasury automation',score:88.4},4:{id:'pulse',name:'PulseCredit',tag:'Alternative underwriting platform',score:87.6},5:{id:'finbridge',name:'FinBridge Labs',tag:'Open-finance connectivity',score:86.8},6:{id:'lumen',name:'Lumen Money',tag:'Cross-border SME banking',score:86.7},7:{id:'orbit',name:'Orbit Finance',tag:'Working-capital marketplace',score:85.9},8:{id:'mint',name:'MintRoute',tag:'B2B settlement rails',score:84.8}};var picked=s.entries.filter(function(e){return e.decision==='shortlist'&&source[e.id]}).map(function(e){var x=source[e.id];return{id:x.id,name:x.name,tag:x.tag,score:x.score,votes:0,totalVotes:5,award:'finalist',nameVerified:true,brandVerified:true,consent:true,juryApproved:true,note:''}}).sort(function(a,b){return b.score-a.score});if(picked.length){picked[0].award='winner';picked[0].votes=4;picked[0].consent=false;categories[0].finalists=picked}}catch(e){}}
  function renderChecks(){var c=activeCategory(),rec=categoryRecipients(c),hasRecipient=rec.length>0,details=hasRecipient&&rec.every(function(f){return f.nameVerified&&f.brandVerified}),consent=hasRecipient&&rec.every(function(f){return f.consent}),jury=hasRecipient&&rec.every(function(f){return f.juryApproved});var checks=[['award',hasRecipient,'Award recipient assigned',hasRecipient?rec.map(function(f){return recipientLabel(f.award)+': '+f.name}).join(', '):'Choose a winner or medal recipient'],['details',details,'Public details verified',details?'Names and brand assets are cleared':'Verify exact name and logo permissions'],['consent',consent,'Recipient consent',consent?'All selected recipients confirmed':'At least one selected recipient has not confirmed'],['jury',jury,'Jury approval',jury?'Authorized sign-off is recorded':'Panel chair approval is still required']];$('#approvalChecks').innerHTML=checks.map(function(ch){return '<div class="wn-check '+(ch[1]?'':'pending')+'"><span>'+(ch[1]?'&#10003;':'!')+'</span><p><b>'+ch[2]+'</b><small>'+ch[3]+'</small></p>'+(ch[1]?'':'<button data-check-action="'+ch[0]+'">Review</button>')+'</div>'}).join('');var ready=checks.filter(function(ch){return ch[1]}).length,score=Math.round((ready/checks.length)*100);$('#categoryReadiness').textContent=score+'%';$('#categoryReadinessBar').style.width=score+'%';$$('[data-check-action]').forEach(function(btn){btn.addEventListener('click',function(){if(rec[0])openFinalist(rec[0].id);else toast('Assign a winner first')})})}
  function renderWinnerBoard(){var root=$('#winnerBoard');root.innerHTML=categories.map(function(c){var rec=categoryRecipients(c),st=categoryStatus(c);var recipient=rec[0];return '<article class="wn-board-item"><span>'+c.name+'</span><h3>'+st.label+'</h3>'+(recipient?'<div class="wn-board-recipient"><div>'+recipientLabel(recipient.award).charAt(0)+'</div><div><b>'+recipient.name+'</b><small>'+recipientLabel(recipient.award)+' - '+recipient.score.toFixed(1)+'</small></div></div>':'<div class="wn-board-empty">No winner assigned yet</div>')+'<div class="wn-board-footer"><span>'+c.finalists.length+' finalists</span><b>'+(c.locked?'Locked':'Draft')+'</b></div></article>'}).join('')}
  function globalMetrics(){var filled=0,verifiedIssues=0,approved=0;categories.forEach(function(c){var rec=categoryRecipients(c);if(rec.length)filled++;if(rec.some(function(f){return !verificationComplete(f)}))verifiedIssues++;if(rec.length&&rec.every(function(f){return f.juryApproved}))approved++});$('#winnerSlots').textContent=filled+' / '+categories.length;$('#verificationCount').textContent=verifiedIssues;$('#approvalCount').textContent=approved+' / '+categories.length;var locked=categories.filter(function(c){return c.locked}).length,allReady=categories.filter(function(c){var rec=categoryRecipients(c);return rec.length&&rec.every(verificationComplete)}).length;var score=Math.round(((filled/categories.length)*35)+((allReady/categories.length)*35)+((locked/categories.length)*30));$('#overallReadiness').textContent=score+'%';$('#overallReadinessBar').style.width=score+'%';$('#readyList').innerHTML='<div><span>&#10003;</span><p><b>Shortlist decisions available</b><small>Finalists are ready for winner assignment</small></p></div><div class="'+(filled===categories.length?'':'pending')+'"><span>'+(filled===categories.length?'&#10003;':'!')+'</span><p><b>Winner slots filled</b><small>'+filled+' of '+categories.length+' categories have recipients</small></p></div><div class="'+(verifiedIssues===0?'':'pending')+'"><span>'+(verifiedIssues===0?'&#10003;':'!')+'</span><p><b>Recipient verification</b><small>'+(verifiedIssues===0?'All public details are approved':verifiedIssues+' categor'+(verifiedIssues===1?'y needs':'ies need')+' verification')+'</small></p></div><div class="'+(locked===categories.length?'':'pending')+'"><span>'+(locked===categories.length?'&#10003;':'!')+'</span><p><b>Winner locks</b><small>'+locked+' of '+categories.length+' category decisions frozen</small></p></div>';$('#copilotHeadline').textContent=filled+' categories have a winner. '+(verifiedIssues?verifiedIssues+' recipient check'+(verifiedIssues===1?'':'s')+' still block a clean announcement.':'All selected recipients are verified.');var missing=categories.filter(function(c){return categoryRecipients(c).length===0}).map(function(c){return c.name}),issue=categories.filter(function(c){return categoryRecipients(c).some(function(f){return !verificationComplete(f)})}).map(function(c){return c.name});$('#copilotDetail').textContent=(issue.length?issue[0]+' needs verification. ':'')+(missing.length?missing[0]+' still needs a final recipient.':'No category is missing a recipient.');$('#finalizeAll').textContent=locked===categories.length?'All categories locked':'Finalize ready categories'}
  function renderAll(){renderTabs();renderTable();renderChecks();renderWinnerBoard();globalMetrics()}
  function openFinalist(id){var c=activeCategory(),f=findFinalist(c,id);if(!f)return;activeFinalist=f;var rank=c.finalists.slice().sort(function(a,b){return b.score-a.score}).findIndex(function(x){return x.id===f.id})+1;$('#drawerName').textContent=f.name;$('#drawerMeta').textContent=c.name+' - '+f.tag;$('#drawerScore').textContent=f.score.toFixed(1);$('#drawerVotes').textContent=f.votes+' / '+f.totalVotes;$('#drawerRank').textContent='#'+rank;$('#drawerAward').innerHTML=optionsFor(c.format,f.award);$('#verifyName').checked=f.nameVerified;$('#verifyBrand').checked=f.brandVerified;$('#verifyConsent').checked=f.consent;$('#verifyJury').checked=f.juryApproved;$('#winnerNote').value=f.note||'';$('#decisionContext').innerHTML='<b>Decision context</b><br>Score rank #'+rank+'. Jury support: '+f.votes+' of '+f.totalVotes+'. '+(rank===1?'This finalist currently leads the normalized ranking.':'A manual winner decision can override score order, but the reason should be documented.');openLayer('winnerDrawer')}
  function openLayer(id){var el=document.getElementById(id);if(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}}
  function closeLayer(id){var el=document.getElementById(id);if(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}}
  function addAudit(title,note,type){var now=new Date(),time=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0'),row=document.createElement('div');row.innerHTML='<span>'+time+'</span><i class="'+(type||'')+'"></i><p><b>'+title+'</b><small>'+note+'</small></p>';$('#auditList').insertBefore(row,$('#auditList').firstChild)}
  function save(){try{localStorage.setItem(stateKey,JSON.stringify({activeCategoryId:activeCategoryId,packGenerated:packGenerated,releaseMode:$('#releaseMode')?$('#releaseMode').value:'scheduled',releaseDate:$('#releaseDate')?$('#releaseDate').value:'2027-06-15',releaseTime:$('#releaseTime')?$('#releaseTime').value:'10:00',sendEmails:$('#sendEmails')?$('#sendEmails').checked:true,publishWebsite:$('#publishWebsite')?$('#publishWebsite').checked:true,socialAssets:$('#socialAssets')?$('#socialAssets').checked:true,categories:categories.map(function(c){return{id:c.id,format:c.format,locked:c.locked,finalists:c.finalists.map(function(f){return{id:f.id,award:f.award,nameVerified:f.nameVerified,brandVerified:f.brandVerified,consent:f.consent,juryApproved:f.juryApproved,note:f.note}})}})}))}catch(e){}}
  function load(){try{var s=JSON.parse(localStorage.getItem(stateKey)||'null');if(!s)return;if(s.activeCategoryId)activeCategoryId=s.activeCategoryId;if(typeof s.packGenerated==='boolean')packGenerated=s.packGenerated;if(s.categories)s.categories.forEach(function(saved){var c=categories.filter(function(x){return x.id===saved.id})[0];if(!c)return;if(saved.format)c.format=saved.format;if(typeof saved.locked==='boolean')c.locked=saved.locked;if(saved.finalists)saved.finalists.forEach(function(sf){var f=findFinalist(c,sf.id);if(!f)return;Object.keys(sf).forEach(function(k){if(k!=='id')f[k]=sf[k]})})});if(s.releaseMode)$('#releaseMode').value=s.releaseMode;if(s.releaseDate)$('#releaseDate').value=s.releaseDate;if(s.releaseTime)$('#releaseTime').value=s.releaseTime;if(typeof s.sendEmails==='boolean')$('#sendEmails').checked=s.sendEmails;if(typeof s.publishWebsite==='boolean')$('#publishWebsite').checked=s.publishWebsite;if(typeof s.socialAssets==='boolean')$('#socialAssets').checked=s.socialAssets}catch(e){}}
  function buildPreview(){var cards=[];categories.forEach(function(c){categoryRecipients(c).forEach(function(f){cards.push('<div class="wn-preview-entry"><span>'+c.name+'</span><b>'+f.name+'</b><small>'+recipientLabel(f.award)+'</small></div>')})});$('#previewCards').innerHTML=cards.join('')||'<div class="wn-preview-entry"><b>No winners assigned yet.</b></div>';openLayer('previewModal')}
  function requestLock(){var c=activeCategory(),rec=categoryRecipients(c);if(c.locked){toast('This category winner is already locked');return}if(!rec.length){toast('Assign a winner before locking');return}if(rec.some(function(f){return !verificationComplete(f)})){toast('Complete recipient verification before locking');$('#approvalSection').scrollIntoView({behavior:'smooth',block:'center'});return}$('#lockCategoryName').textContent=c.name;$('#lockConfirm').checked=false;$('#confirmLock').disabled=true;openLayer('lockModal')}
  function exportCsv(name,lines){var blob=new Blob([lines.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
  function exportWinners(){var lines=['category,award,recipient,score,status'];categories.forEach(function(c){categoryRecipients(c).forEach(function(f){lines.push('"'+c.name+'","'+recipientLabel(f.award)+'","'+f.name.replace(/"/g,'""')+'","'+f.score.toFixed(1)+'","'+(c.locked?'Locked':'Draft')+'"')})});exportCsv('etb2b_awards-winners.csv',lines);toast('Winner list downloaded')}
  function exportAudit(){var lines=['time,event,detail'];$$('#auditList>div').forEach(function(row){var t=row.querySelector('span'),b=row.querySelector('b'),s=row.querySelector('small');lines.push('"'+(t?t.textContent:'')+'","'+(b?b.textContent:'')+'","'+(s?s.textContent.replace(/"/g,'""'):'')+'"')});exportCsv('etb2b_awards-winner-audit.csv',lines);toast('Audit CSV downloaded')}
  function renderPack(){if(packGenerated){$('#packStatus').textContent='Ready';$('#packStatus').classList.add('green');$('#certStatus').textContent='Approved winners ready';$('#emailStatus').textContent='Personalized drafts refreshed';$('#webStatus').textContent='Winner gallery synced';$('#socialStatus').textContent='Creative set refreshed'}}
  seedStartupFromShortlist();load();renderAll();renderPack();
  $('#awardFormat').addEventListener('change',function(){var c=activeCategory();if(c.locked)return;c.format=this.value;c.finalists.forEach(function(f){f.award='finalist'});addAudit('Award format changed',c.name+' changed to '+this.options[this.selectedIndex].text+'.','warn');renderAll();save();toast('Award format updated')});
  $('#seedFromRanking').addEventListener('click',function(){var c=activeCategory();if(c.locked){toast('Locked category cannot be changed');return}var ranked=c.finalists.slice().sort(function(a,b){return b.score-a.score});c.finalists.forEach(function(f){f.award='finalist'});if(c.format==='medals'){if(ranked[0])ranked[0].award='gold';if(ranked[1])ranked[1].award='silver';if(ranked[2])ranked[2].award='bronze'}else if(c.format==='winner-runner'){if(ranked[0])ranked[0].award='winner';if(ranked[1])ranked[1].award='runner-up'}else if(ranked[0])ranked[0].award='winner';addAudit('Ranking seed applied',c.name+' award assignments seeded from normalized ranking.','good');renderAll();save();toast('Seeded from ranking')});
  $('#clearAssignments').addEventListener('click',function(){var c=activeCategory();if(c.locked){toast('Locked category cannot be changed');return}c.finalists.forEach(function(f){f.award='finalist'});addAudit('Assignments cleared',c.name+' returned to finalist-only state.','warn');renderAll();save();toast('Assignments cleared')});
  $('#saveDrawer').addEventListener('click',function(){if(!activeFinalist)return;var c=activeCategory(),old=activeFinalist.award;assignAward(c,activeFinalist,$('#drawerAward').value);activeFinalist.nameVerified=$('#verifyName').checked;activeFinalist.brandVerified=$('#verifyBrand').checked;activeFinalist.consent=$('#verifyConsent').checked;activeFinalist.juryApproved=$('#verifyJury').checked;activeFinalist.note=$('#winnerNote').value.trim();addAudit('Finalist details updated',activeFinalist.name+' verification and award assignment saved.','good');if(old!==activeFinalist.award)addAudit('Award assignment changed',activeFinalist.name+' set to '+recipientLabel(activeFinalist.award)+'.','good');save();renderAll();closeLayer('winnerDrawer');toast('Finalist saved')});
  $('#lockCategory').addEventListener('click',requestLock);$('#lockConfirm').addEventListener('change',function(){$('#confirmLock').disabled=!this.checked});$('#confirmLock').addEventListener('click',function(){var c=activeCategory();c.locked=true;addAudit('Winner locked',c.name+' final decision frozen with '+categoryRecipients(c).map(function(f){return recipientLabel(f.award)+': '+f.name}).join(', ')+'.','good');save();renderAll();closeLayer('lockModal');toast('Winner decision locked')});
  $('#finalizeAll').addEventListener('click',function(){var count=0;categories.forEach(function(c){var rec=categoryRecipients(c);if(!c.locked&&rec.length&&rec.every(verificationComplete)){c.locked=true;count++}});if(count){addAudit('Ready categories finalized',count+' category winner decision'+(count===1?'':'s')+' locked.','good');renderAll();save();toast(count+' ready categor'+(count===1?'y':'ies')+' locked')}else toast('No additional categories are ready to lock')});
  $('#saveWinners').addEventListener('click',function(){save();toast('Winner decisions saved')});$('#previewAnnouncement').addEventListener('click',buildPreview);$('#previewFromCard').addEventListener('click',buildPreview);$('#exportWinnerList').addEventListener('click',exportWinners);$('#exportAudit').addEventListener('click',exportAudit);
  $('#generatePack').addEventListener('click',function(){packGenerated=true;renderPack();save();addAudit('Celebration pack refreshed','Certificates, winner emails, website gallery, and social assets prepared from current approved data.','good');toast('Celebration pack refreshed')});
  $$('[data-pack]').forEach(function(btn){btn.addEventListener('click',function(){var map={cert:'Certificates preview ready',email:'Winner email drafts opened',web:'Winner gallery preview opened',social:'Social creative preview ready'};toast(map[this.dataset.pack])})});
  ['releaseMode','releaseDate','releaseTime','sendEmails','publishWebsite','socialAssets'].forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('change',function(){save();if(id==='releaseDate'){var d=new Date(this.value+'T00:00:00');if(!isNaN(d))$('#announcementKpi').textContent=d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}toast('Release settings saved')})});
  $('#reviewWinnerIssues').addEventListener('click',function(){var c=categories.filter(function(cat){return categoryRecipients(cat).some(function(f){return !verificationComplete(f)})||categoryRecipients(cat).length===0})[0];if(c){activeCategoryId=c.id;renderAll();document.querySelector('.wn-category-strip').scrollIntoView({behavior:'smooth',block:'start'});toast(c.name+' needs attention')}else toast('No winner blockers found')});
  $('#prepareSafePack').addEventListener('click',function(){packGenerated=true;renderPack();save();toast('Draft assets prepared without publishing')});
  $('#openCopilot').addEventListener('click',function(){$('#copilotPanel').classList.add('open')});$('#closeCopilot').addEventListener('click',function(){$('#copilotPanel').classList.remove('open')});$$('.wn-copilot-prompts button').forEach(function(btn){btn.addEventListener('click',function(){var c=activeCategory(),rec=categoryRecipients(c),unverified=rec.filter(function(f){return !verificationComplete(f)}).length,locked=categories.filter(function(x){return x.locked}).length;var answers={blockers:'Announcement is blocked by any category without a recipient, any selected recipient missing verification or jury sign-off, and any category you require to be locked before release.',category:rec.length?(unverified?c.name+' has a recipient, but '+unverified+' selected recipient check'+(unverified===1?' is':'s are')+' still open.':'This category has a verified recipient and is ready to lock.'):'No recipient is assigned in '+c.name+'. Choose a winner before lock.',embargo:'Before the embargo lifts, verify exact public names, confirm logo rights and winner consent, record jury approval, freeze winner decisions, then regenerate certificates and website assets.',assets:packGenerated?'The celebration pack has been generated from the current winner data. Re-run it after any recipient or spelling change.':'Draft certificates, emails, website cards, and social creatives can be prepared now without publishing. Generate the pack after winner details are verified.'};$('#copilotAnswer').textContent=answers[this.dataset.prompt]})});
  $$('[data-close]').forEach(function(el){el.addEventListener('click',function(){closeLayer(this.dataset.close)})});document.addEventListener('keydown',function(e){if(e.key==='Escape'){$$('.wn-modal.open,.wn-drawer.open').forEach(function(el){closeLayer(el.id)});$('#copilotPanel').classList.remove('open')}})
})();
